### ISSUE TITLE
구동중인 ec2 인스턴스 를 리포트 해주는 기능 정리 필요

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/cloud-usage#13]
구동중인 인스턴스는 잘 리포트 되고 있고 유용함.
현재 리포트 되는 정보들이 많아서 정리가 필요해 보임.

- 각 계정별로 최소한 1분 정도의 차이를 두고 개시가 되면 좋을것 같음
- 각 코드를 카피 해서 인지 Account: [bigdata@kookmin.ac.kr](mailto:bigdata@kookmin.ac.kr) 이부분이 bigdata 인 경우가 많아서 실제 계정에 맞게끔 수정 필요
- bigdata@kookmin.ac.kr 계정은 인스턴스를 자주 사용하는 계정인 만큼 하루 2번 공지가 오는게 적당한듯 한데, 다른 계정들은 하루 한번 아침에만 공지가 와도 좋을것 같음.
-

**Comment by Kim-Yul** [comment]
말씀해주신 부분 중 2번은 재일님께서 수정하신 것으로 판단되어 1번과 3번만 수정하겠습니다.

**Comment by Kim-Yul** [comment]
- 가장 인스턴스가 적은 것부터 순서대로 1분 간격을 주어 알림이 될 수 있도록 수정하였습니다.
    bigdata+prod@kookmin.ac.kr
    spotrank@kookmin.ac.kr
    bigdata@kookmin.ac.kr
- bigdata@kookmin.ac.kr 계정에서만 아침에 오도록 현재 수정 중에 있습니다.
spotrank@kookmin.ac.kr 계정은 변경 완료하였고, bigdata+prod@kookmin.ac.kr 계정은 계정이 없어 접근할 수 없기에 내일 오전 중에 수정할 예정입니다.

**Comment by Kim-Yul** [comment]
- bigdata+prod@kookmin.ac.kr 계정에서 오전에만 알림이 오도록 수정 완료했습니다.

이슈 처리 완료하여 close 하겠습니다!
