### ISSUE TITLE
GCP 가격 모니터링 모듈 공지 시간 변경하기

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/cloud-usage#14]
혼자서 오전 11시 30분에 오니 다른 것들 처럼 오전 9시 10분 정도에 공지가 오면 좋을듯 함.

**Comment by red0sena** [comment]
GCP 가격 모니터링 시간을 9시 10분으로 변경하였고  정상작동 확인하였습니다. close하겠습니다.
