### ISSUE TITLE
S3 bucket management

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#17]
#16 해당 작업과 관련하여 전달받았으며 내용 확인하였습니다.
코드 상에 변화가 생길 것 같아 새로 이슈를 작성하여 관리하고 진행하겠습니다.
우선 현재 수정할 사항은 aws 내의 event bridge 시간 변경 및 list_to_archive_from_s3_bucket 내에 간단한 메세지 수정이 필요한 것 같습니다.
이와 관련한 작업을 진행하기 전 미리 이슈를 남겨둡니다.

**Comment by Kim-Yul** [comment]
## S3 management 보완
<img width="1789" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/94349b71-a69c-4cf2-89ba-a4358d45e044">

s3 리스트 알림 내용을 확인한 결과, 이전과 달라진 게 없는 듯한 결과가 출력된 것을 확인했습니다.
이에 s3에 들어가서 확인해보니, 실제로는 glacier로 옮겨진 게 맞습니다.
다만, 현재 코드 상에서는 s3 bucket으로 잡혀 있는 것들이 모두 출력되다 보니 glacier로 이동된 것을 판별하지 못해 현재와 같은 예상치 못한 결과가 나온 것 같습니다.

<img width="346" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/b90f8a99-e2b4-41b2-b855-57743cfdb305">

위 경우 s3 bucket이지만, 실제로는 glacier로 옮겨졌고 glacier 콘솔에는 확인이 불가능합니다. 그래서 분류 자체는 s3 bucket이며 glacier에 저장되어 있다는 것으로 확인됩니다.

---

### comment
위의 내용을 토대로 솔루션을 내어 보자면, 실제 glacier로 이동 됐는지 아닌지를 판별하는 object가 있어서 이를 이용하여 s3인 경우에만 출력할 수 있도록 변경이 필요할 것 같습니다.
이렇게 하면 실제로 glacier로 이동된 파일은 제외되고 원하던 list 출력이 가능할 것 같습니다.
또한 이미 제대로 glacier로 이동되었기 때문에 서버를 켜서 glacier로의 이동은 불필요할 것 같습니다.
수정 사항만 수정해둘까 합니다. 아래는 현재 진행할 수정사항입니다.

    1. 현재 코드 설명 추가
    2. object 중 class 판별하여 s3 bucket만 리스트로 출력

덧붙여서 저희 s3 bucket 내에 public으로 공개된 파일이 있었는데, 실제로 작업할 때 이 public 자료도 모두 glacier로 옮겨버렸습니다.
혹시 public 자료는 s3 bucket으로 보존해야하는 게 있었을까요? 옮겨야 하는 게 있다면 다시 s3 bucket으로 옮겨두고, list 추출 시 public 자료는 glacier로 옮기지 않도록 하는 내용도 추가하겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 그런 이유가 있었구나. make sense. 표시를 해줄때 glacier 에 있는건 빼줘도 좋겠다.
그런데 한가지 더 확인할건 실제로 과금 되는 걸 보면 "USW2-TimedStorage-ByteHrs = 2.4180643347"
전처럼 비슷한 금액이 과금 되는것 같은데.. 이 부분도 한번 확인해줄래?

**Comment by Kim-Yul** [comment]
해당부분 확인해보았습니다.
우선 해당 과금은 s3 standard 스토리지에 데이터가 저장된 GB-시간 수에 따라 비용이 발생합니다.
이에 최근 usage 요금을 살펴보았더니 보통 2.3달러정도 되는 것 같습니다.

      9월 4일 - USW2-TimedStorage-ByteHrs = 2.4180643347
      9월 3일 - USW2-TimedStorage-ByteHrs = 1.7458246946
      9월 2일 - USW2-TimedStorage-ByteHrs = 1.4678425633
      9월 1일 - USW2-TimedStorage-ByteHrs = 2.3471489577 
      8월 31일 - USW2-TimedStorage-ByteHrs = 2.3466518414
      8월 30일 - USW2-TimedStorage-ByteHrs = 2.346124458
      8월 29일 - USW2-TimedStorage-ByteHrs = 2.3455674514
      8월 28일 - USW2-TimedStorage-ByteHrs = 2.3449470696
      8월 27일 - USW2-TimedStorage-ByteHrs = 2.3443787197
      8월 26일 - USW2-TimedStorage-ByteHrs = 2.3557452266

이 요금을 확인하니 그럼 옮겨진 glacier 요금은 측정이 되지 않는 것인지 찾아보았더니 모든 항목에서 찾아볼 수는 없었지만, 일부 날짜에서 해당 내용을 발견할 수 있었습니다.

      9월 5일 - USW2-TimedStorage-GlacierByteHrs = 0.0019427692
      9월 4일 - USW2-TimedStorage-GlacierByteHrs = 0.0019427692
      9월 3일 - USW2-TimedStorage-GlacierByteHrs = 0.0019427692
      9월 2일 - X

제가 다 찾지 못했을 가능성도 있습니다만, 가끔씩 해당 항목이 없는 날도 있는 것 같습니다.

요금이 왜 늘었을지 근본적으로 찾아보기 위해서 glacier로 옮겼던 날을 확인해보았습니다.

      8월 17일 - USW2-TimedStorage-ByteHrs = 1.4675157776
      8월 18일 - USW2-TimedStorage-ByteHrs = 1.6213787524
      8월 19일 - USW2-TimedStorage-ByteHrs = 2.3520040242
      8월 20일 - USW2-TimedStorage-ByteHrs = 2.3525549763

8월 18일에 옮겼는데, 이 날을 기점으로 과금 비용이 증가하였습니다.
이것을 보고 추측한 것은 standard 스토리지의 값만 측정하는 것이 아니라, glacier가 중복 체크가 되는 것인가 하는 의문이 들었습니다. usage-report를 확인해보았을 때, 그냥 aws에서 인식이 되는 값을 report 해주는 것 같은데 해당 부분에서 왜 급격하게 비용이 증가되었는지 원인을 찾지 못했습니다.
다만 aws 청구서를 확인했을 때, 8월 동안 s3의 용량이 670GB였다가, 9월에는 90GB 안으로 줄어든 것을 확인했는데, glacier로의 이동은 확실해 보입니다.
리스트를 출력하는 코드를 작성하면서, 전체 용량을 파악해볼까 하는 생각도 하고 있습니다.
우선 알아본 바는 이렇습니다.

**Comment by kmu-leeky** [comment]
오케이. 유림아 확인땡큐. 실제로 과금이 되는게 줄지 않은게 이상하네. 실제로 저장되는 파일의 용량은 670 에서 90으로 줄어든것 같은데.. 조금 만 더 확인해보고 그래도 모르겠으면 과금 담당하는곳에 한번 물어보는것도 괜찮겠다.

**Comment by Kim-Yul** [comment]
## S3 버킷 분석

실제 S3 내에서 glacier로 옮겨졌어야 하는 버킷의 용량이 실제로 전부 옮겨지지 않은 모양입니다.
대표적으로 용량이 큰 몇 가지만 사례로 들어 정리하였습니다.

8월 17일을 기준으로 glacier로 넘어가야하는 리스트에 속한 것들의 현재 저장 현황입니다.
6 ['ayci', 28628.78, 244.41] -> Standard : 28.63GB, Glacier : 244.41MB
22 ['dl-converted-models', 55499.63, 22781.68] -> Standard : 55.50GB, Glacier : 22.78GB
32 ['jg-inf-compiled-model', 61192.77, 6349.39] -> Standard : 61.20GB, Glacier : 6.35GB
69 ['spotrank-figure', 184852.83, 3036.53] -> Standard : 184.85GB, Glacier : 3.04GB

6번 버킷의 일부 파일입니다.
    2023-08-24 06:16:20+00:00 GLACIER
    2022-08-10 04:50:33+00:00 STANDARD
    2022-05-27 02:31:56+00:00 STANDARD
    2022-05-27 02:40:32+00:00 STANDARD
보시면 단 하나의 파일만 GLACIER로 이동되었고, 나머지는 수정일자가 최근이 아님에도 STANDARD로 되어 있습니다.
그러나 GLACIER로 옮겨간 파일의 수정일자가 최신화되면서, 해당 버킷은 현재 기준으로 Glacier로 옮겨질 대상 파일이 아닙니다.

22번 버킷의 일부 파일입니다.
    172 2023-08-24 06:35:10+00:00 GLACIER
    173 2023-08-24 06:35:22+00:00 GLACIER
    174 2023-08-24 06:35:34+00:00 GLACIER
    175 2022-03-16 04:11:45+00:00 STANDARD
    176 2022-03-16 04:11:45+00:00 STANDARD
    177 2022-03-16 04:11:45+00:00 STANDARD
174번 파일을 기준으로 22.78GB가 Glacier로 이동되었으며, 175번부터 767번까지의 55.5GB의 파일은 Standard에 남아 있는 상황입니다.
이 파일 역시 수정일자가 최신화되어 현재 기준 glacier로 옮겨지지 않습니다.

32번 버킷의 일부 파일입니다.
    104 2023-08-24 07:18:20+00:00 GLACIER
    105 2023-08-24 07:18:22+00:00 GLACIER
    106 2022-12-28 04:20:39+00:00 STANDARD
    107 2022-12-28 04:20:40+00:00 STANDARD
    108 2022-12-28 04:20:40+00:00 STANDARD
105번 파일을 기준으로 6.35GB의 파일이 Glacier로 이동되었고, 106번부터 635번까지의 61.2GB는 Standard에 남아있습니다.
최신화 파일이기에 현재 기준으로 glacier로 옮겨지지 않습니다.

69번 버킷의 일부 파일입니다.
    1 2023-08-24 08:06:54+00:00 GLACIER
    2 2023-08-24 08:06:54+00:00 GLACIER
    3 2022-07-12 11:36:06+00:00 STANDARD
    4 2023-08-24 08:06:58+00:00 GLACIER
    5 2023-08-24 08:06:58+00:00 GLACIER
    6 2023-08-24 08:06:58+00:00 GLACIER
    7 2023-08-24 08:06:58+00:00 GLACIER
    8 2023-08-24 08:06:59+00:00 GLACIER
    9 2023-08-24 08:06:59+00:00 GLACIER
    10 2022-07-13 01:21:07+00:00 STANDARD
    11 2023-08-24 08:07:00+00:00 GLACIER
    12 2023-08-24 08:07:00+00:00 GLACIER
    13 2022-07-11 13:06:02+00:00 STANDARD
    14 2022-07-12 06:47:04+00:00 STANDARD
    15 2022-07-12 02:38:44+00:00 STANDARD
이 파일의 경우 10개의 파일 3.04GB는 glacier로 이동되었고, 이 외의 68개의 파일 184.85GB는 Standard에 남았습니다.
이 역시 최신화되었기에 현재 Glacier로 옮겨지는 대상이 아닙니다.

---

Lambda로 실행하면서 15분 limit이 지나 끊어진 버킷의 경우 위와 같은 결과를 도출한 듯 보입니다.
10월 S3 정기관리 이전에 ec2 인스턴스를 통해 8월 24일의 최신화를 가진 버킷들은 glacier로 넘어가도록 수동 작업이 필요할 것 같습니다.
또한, 이 외에도 넘어가지 않았을 버킷이 분명 존재하지만, 제일 큰 용량을 차지하는 4개를 선정하여 정리하였습니다.

**위의 4개 버킷 및 나머지 버킷들 중 8월 24일의 최신화를 가진 버킷은 모두 glacier로 옮기는 작업을 ec2를 통해 진행하고자 합니다.
그래도 괜찮을까요?**

또한, lambda 내에서 작업할 경우, 하나의 파일이 용량이 커서 중간에 타임아웃이 될 때는 그 버킷의 수정 일자가 최신화되기 때문에 원하는대로 100% 작동하는 것이 어려울 듯합니다. lambda가 아닌 다른 방법이 필요하지 않을까 생각됩니다. 확인부탁드립니다.

**Comment by kmu-leeky** [comment]
오케이. 정상 동작을 안했구나. 잘 확인해봤다.
우선 EC2 서버에서 계속 옮기는 작업을 진행하자. 용량 큰것 뿐만 아니라 오래된 것들은 이번에 싹다 glacier 로 옮기자.

**Comment by mh3ong** [comment]
현재 Glacier로 넘기는 기준이 뭔가요?
기존에 제가 알기로는 6개월 이상 접근이 없으면 넘어가는 것으로 알고 있는데
실험에 사용되고있는 bucket이 Glacier로 넘어가서 문의드립니다.
(check 필요 bucket -> ddps-lab-scpc-bucket)

**Comment by kmu-leeky** [comment]
글래시어로 옮기는 것도 쉽지 않구나..
어쩌면 다른 방법을 생각해봐야 할수도 있겠다.
수동으로 이관하는 과정중에 불필요하게 glacier 로 옮겨진건 없는지 도 한번 확인해보자.

**Comment by Kim-Yul** [comment]
우선 사용 중이라고 하신 `ddps-lab-scpc-bucket` 은 s3 standard class 로 옮겨두었습니다.
말씀하신 대로 6개월 기준이 맞지만, 잘못 옮겨진 버킷이 맞는 것 같습니다.
기존에 옮겨야 하는 버킷으로 착각하여 실수하였습니다.

현재 옮긴 버킷을 확인 중입니다.
확인해보니 예상보다 몇 개가 더 옮겨져 있습니다.
그런데 그 glacier로 변경된 날짜가 8월 24일로 확인되는 것을 보아 지난 번 처음 glacier로 옮겼을 당시에 lambda를 통해 잘못 이관된 게 몇 개 있는 것 같습니다..
해당 리스트 확인해보고 다시 이슈드리겠습니다.

**Comment by Kim-Yul** [comment]
녹색 배경색이 입혀진 버킷은 8월 17일 기준 glacier로 옮겨져야 했던 목록입니다.
진하게 표시된 byte는 현재 standard 혹은 glacier에 저장된 용량을 의미합니다.

`ddps-lab-scpc-bucket` 외에 잘못 옮겨진 버킷은 없습니다.
<img width="683" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/4a2960ef-3848-43dc-965f-d22d3158a77d">

**Comment by Kim-Yul** [comment]
10월 1일 날짜에 출력된 s3 bucket 리스트는 glacier로 이동된 버킷마저 출력합니다.
현재 standard bucket 만 출력할 수 있게끔 작성하는 코드를 수정 완료하였습니다.
그리고 이전부터 우려하였던 코드의 중복 부분을 수정하고자 lambda layer로 형식을 바꾸어 볼까 합니다.
테스트 해보고 유의미한 결과가 나온다면 수정 전에 이슈 남기겠습니다.

추가로 10월 5일인 내일 진행하는 s3 management는 잠시 중단해두어도 괜찮을까요?
glacier로 옮기는 부분에서 조금 수정하고 진행해보고 싶습니다.

**Comment by kmu-leeky** [comment]
s3 리스트는 스탠다드만 보내면 될것 같아.
지금 glacier 로 이관은 다 마무리 되었다고 봐도 될까?
코드 중복 이슈를 람다  layer 로 해결하는건 우선순위를 낮추어도 괜찮을것 같아.
작업 노력 대비 얻어지는게 크지는 않을것 같아.

스냅샷을 관리하는 방안에 조금 더 우선순위를 두자.

**Comment by kmu-leeky** [comment]
billing dashboard 를 확인해보니, S3 라고 나오는것들에 실제는 ECR 에 저장된 이미지들이 많은 부분을 차지하는것 같아.
불필요한 ECR 이미지들을 삭제할 필요도 있겠다.
ECR 에 대한 부분도 S3 처럼 조사되는 과정이 필요할것 같아.

<img width="527" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/17699616/0e6265ca-9059-440f-9fa9-ce318ec4ad18">

**Comment by mh3ong** [comment]
Seoul region의 0.09$ 는 이번 wosc 관련 리소스입니다.
삭제하도록 하겠습니다.
또한 GCP의 경우에도 모든 요금이 0원이 나오도록 조치하겠습니다.

**Comment by Kim-Yul** [comment]
기존 lambda에서 진행하려고 하였던 glacier로 옮기는 작업이 lambda에서 진행하는 것이 어려울 것으로 보아,
ec2에서 소스파일을 실행하여 진행하는 방향으로 바꾸었습니다.
자동화 코드 작업 완료하였으며, 슬랙으로 전송되는 것도 확인하였습니다.
다만, 홍콩 리전이 t3.micro였기에 다른 리전에서 t2.micro 로 실행이 가능한지, 그리고 실행 시간에 차이가 있는지 확인해본 이후 작업 마무리할 예정입니다.
변경된 내용에 맞추어 기존 코드에 수정사항이 생겼고, 수정 후 다시 커밋하겠습니다.

작업 전에 아래의 내용 수정해도 되는지 확인부탁드립니다.
1. 기존 lambda 자동화 코드 -> ec2 자동화 코드로 변경
2. git에 올라간 s3 management 중 사용하지 않는 파일 삭제
3. s3를 관리하는 모든 파일을 S3_Management 디렉토리 아래로 이동

추가로 ec2에 작업하게 되면서 IAM의 access key와 secret access key 정보가 필요하게 됩니다.
해당 부분은 비워둔 채로 코드를 커밋할 예정이며, 자동화 코드 사용 전 어떤 정보가 필요한지 메뉴얼하여 다시 남기겠습니다.

**Comment by Kim-Yul** [comment]
s3 management 중 ec2를 이용해서 자동화를 진행하는 부분에 대하여 의견 여쭙습니다.

현재는 수동으로 ec2를 켜서 실행파일을 작동시키고 있습니다. 
이럴 경우 제가 해결하지 못한 부분은 스냅샷을 이용해서 ec2를 수동으로 생성하고 스크립트를 이용해서 파이썬 자동화 코드를 실행해야만 합니다.
무엇보다 보안적으로도 취약한 부분이 있습니다.

재일님과 경환님께서는 이 부분을 보시고 instance를 생성할 때 user data와 lambda를 이용해서 자동화로 할 수 있다고 조언해주셨습니다. 
처음 해보는 것이긴 하지만, 이를 이용해서 한 번 자동화해보고 싶어서 조금의 시간을 더 가져도 될지 교수님께 양해를 구합니다.

한 번 알아보고 적용해보아도 괜찮을까요? #23

**Comment by kmu-leeky** [comment]
응 유림아 가능한 방법인것 같아.
더 바람직한 방법이기도 하고.

지금 이슈 및 PR 이 길어지니 우선 지금 이슈 클로즈, PR 클로즈 및 머지를 하자.

그리고 새로운 이슈를 만들어서, 위 코멘트에서 이야기한 내용을 진행하도록 정리해보자.

**Comment by Kim-Yul** [comment]
> 지금 이슈 및 PR 이 길어지니 우선 지금 이슈 클로즈, PR 클로즈 및 머지를 하자.
> 그리고 새로운 이슈를 만들어서, 위 코멘트에서 이야기한 내용을 진행하도록 정리해보자.

위를 반영하여, 현재 이슈 클로즈합니다.
