### ISSUE TITLE
의문의 EventBridge Rule로 인한 불필요한 Lambda Invocation 생성

### ISSUE THREAD

**Issue by mh3ong** [ddps-lab/cloud-usage#20]
WWW EventBridge 관련 실험하다가 알게된 내용입니다.
![image](https://github.com/ddps-lab/cloud-usage/assets/49053299/24d28ac1-30a4-44d2-9bb2-5e1060232e5a)
![image](https://github.com/ddps-lab/cloud-usage/assets/49053299/1d691667-b97b-4b36-9ca6-bab2cd86279f)

kmubigdata계정의 모든 Region에는 저런 "TerminatedInstance"라는 Rule과, 해당 Rule의 Target인 "ec2-terminated-instances"라는 Lambda Function이 존재하고 있습니다.

TerminatedInstance를 보니, terminated가 되는 모든 event는 ec2-terminated-instances에 event를 전달하고, ec2-terminated-instances는 삭제된 instance 정보를 기록하여 지금은 존재하지 않는 bucket인 kmu-ec2-terminated-instances에 json형식으로 저장합니다.

이 Lambda Function으로 인해 WWW2024 실험중, describe instance에 대한 불피요한 API Throttling이 유발될 것으로 보여 모든 리전에서 제거하도록 하겠습니다.
@red0sena 

---

WWW2024 실험으로 인해 이 lambda function이 실행되었지만, 실패만 한 모습
![image](https://github.com/ddps-lab/cloud-usage/assets/49053299/692c9796-a0c3-4fe7-b6d5-58628d014e2e)

**Comment by mh3ong** [comment]
![image](https://github.com/ddps-lab/cloud-usage/assets/49053299/3ad73a15-50a1-4836-8f22-bd9479b1638e)
이런것도 존재해서 삭제하였습니다.

@Kim-Yul eventbridge rule 목록을 분석하여 불필요한 내용이 rate와 같이 쓸데없이 지속적으로나 불필요한 trigger가 발생되어 lambda function을 실행하는지 등을 전수조사할 필요가 있어 보입니다.

**Comment by kmu-leeky** [comment]
응 무현아. 잘 발견했다.

@Kim-Yul  은 무현이가 이야기한 내용을 바탕으로 새로운 이슈를 만들어서 중간 상황 기록해주면 좋을것 같아.

해당 이벤트는 5년 전에 만들어졌네. 2018년 즘인듯 한데.. 어떤 이유 였는지 딱히 기억이 나지는 않네.
그냥 삭제해버려도 되겠다.

**Comment by mh3ong** [comment]
이 issue에 해당되는 내용은 삭제완료되어 issue close하겠습니다.
