### ISSUE TITLE
ECR 분석

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#22]
> billing dashboard 를 확인해보니, S3 라고 나오는것들에 실제는 ECR 에 저장된 이미지들이 많은 부분을 차지하는것 같아.
> 불필요한 ECR 이미지들을 삭제할 필요도 있겠다.
> ECR 에 대한 부분도 S3 처럼 조사되는 과정이 필요할것 같아.

- ECR 과 S3 요금의 연관성
- 계정 내 ECR 총 용량 및 생성일자 등 분석
위의 과정으로 우선 조사 진행하겠습니다.

**Comment by kmu-leeky** [comment]
유림아. 이 부분은 우선 유림이가 시작하지는 말고 있어보자.

**Comment by seungwoo1124** [comment]
세 이슈 할당받은거 전부 확인 했습니다.
목요일 세미나 준비로 깊게 보진 못했고 내일 저녁부터 본격적으로 진행하도록 하겠습니다.

**Comment by seungwoo1124** [comment]
### ====== REGION ap-northeast-2 total size : 0.000 GB ======
repository name : lambda-container-example-yoon / repository size : 0.000 GB / last pushed date : 1111-01-01 01:01:01

### ====== REGION us-east-1 total size : 5.544 GB ======
repository name : ys-profet_for_lambda_container / repository size : 5.544 GB / last pushed date : 2021-09-05 01:16:41

### ====== REGION us-east-2 total size : 0.757 GB ======
repository name : billing / repository size : 0.628 GB / last pushed date : 2023-03-27 14:41:50
repository name : fargate-image / repository size : 0.130 GB / last pushed date : 2020-05-13 16:02:12

### ====== REGION us-west-2 total size : 769.042 GB ======
repository name : ria-onnx_gpt / repository size : 12.557 GB / last pushed date : 2023-10-26 11:16:09
repository name : ria-onnx_bert / repository size : 51.259 GB / last pushed date : 2023-10-25 17:39:27
repository name : lambda_archive_module / repository size : 30.805 GB / last pushed date : 2022-11-05 22:52:40
repository name : convert_torch_intel_tvm / repository size : 35.529 GB / last pushed date : 2022-09-06 15:33:00
repository name : convert_torch_arm_tvm / repository size : 27.831 GB / last pushed date : 2022-09-06 15:31:42
repository name : convert_torch_onnx / repository size : 19.471 GB / last pushed date : 2022-09-06 14:12:33
repository name : serving_intel_tvm / repository size : 13.887 GB / last pushed date : 2022-09-06 13:32:33
repository name : serving_arm_tvm / repository size : 9.724 GB / last pushed date : 2022-09-06 13:27:32
repository name : serving_intel_torch / repository size : 11.675 GB / last pushed date : 2022-09-06 13:15:29
repository name : serving_intel_onnx / repository size : 16.943 GB / last pushed date : 2022-09-06 13:12:55
repository name : serving_arm_torch / repository size : 7.034 GB / last pushed date : 2022-09-06 13:11:47
repository name : serving_arm_onnx / repository size : 7.782 GB / last pushed date : 2022-09-06 13:09:44
repository name : lambda-container-example / repository size : 3.062 GB / last pushed date : 2022-08-14 22:19:43
repository name : lambda_check_module / repository size : 9.396 GB / last pushed date : 2022-08-09 15:13:37
repository name : aws_inferentia / repository size : 3.476 GB / last pushed date : 2022-06-22 16:11:13
repository name : mxnet_lambda_container_arm / repository size : 43.851 GB / last pushed date : 2022-06-16 13:55:18
repository name : serving_mxnet_bert_arm / repository size : 2.936 GB / last pushed date : 2022-06-16 01:33:54
repository name : onnx_lambda_container_arm / repository size : 6.296 GB / last pushed date : 2022-06-14 16:20:31
repository name : serving_arm_base / repository size : 1.177 GB / last pushed date : 2022-05-27 15:59:28
repository name : lambda_optimize_serving / repository size : 10.397 GB / last pushed date : 2022-05-24 15:11:42
repository name : torch_profiler_arm / repository size : 5.910 GB / last pushed date : 2022-04-22 15:54:08
repository name : tvm_lambda_container / repository size : 163.220 GB / last pushed date : 2022-04-14 13:45:09
repository name : torch_lambda_container_arm / repository size : 2.795 GB / last pushed date : 2022-04-13 16:21:46
repository name : onnx_lambda_container / repository size : 21.492 GB / last pushed date : 2022-03-11 16:41:32
repository name : tvm_lambda_container_arm / repository size : 38.758 GB / last pushed date : 2022-03-08 15:38:05
repository name : torch_lambda_container / repository size : 18.752 GB / last pushed date : 2022-03-08 15:01:45
repository name : mxnet_lambda_container / repository size : 53.914 GB / last pushed date : 2022-03-07 19:35:04
repository name : tflite_lambda_container_arm / repository size : 1.276 GB / last pushed date : 2022-01-24 15:32:11
repository name : tflite_lambda_container / repository size : 2.271 GB / last pushed date : 2022-01-23 00:44:47
repository name : jgtfservingmobilenetv2201ea088/tensorflowinferencefunction402a36b7repo / repository size : 1.418 GB / last pushed date : 2022-01-10 14:07:59
repository name : jgxgboostlambdafb3860c3/xgboostinferencefunction8eed4b10repo / repository size : 0.727 GB / last pushed date : 2022-01-07 17:21:28
repository name : jgtfservinglambdab907d6f5/tensorflowinferencefunction402a36b7repo / repository size : 1.564 GB / last pushed date : 2022-01-07 17:00:00
repository name : jgscikitlambdad958a065/scikitlearninferencefunctionc862108arepo / repository size : 0.350 GB / last pushed date : 2022-01-07 16:59:58
repository name : jgsamfaae96cb/helloworldfunction19d43fc4repo / repository size : 0.176 GB / last pushed date : 2022-01-05 13:04:10
repository name : jg-graviton-tensorflow / repository size : 12.233 GB / last pushed date : 2022-01-05 13:01:48
repository name : tvm_lambda_container_origin / repository size : 1.280 GB / last pushed date : 2021-12-31 15:02:49
repository name : sungjae-sps-lambda / repository size : 2.240 GB / last pushed date : 2021-11-04 17:40:00
repository name : jg-seq-efficientnet / repository size : 10.614 GB / last pushed date : 2021-11-01 13:52:15
repository name : jg-seq-ensemble / repository size : 16.921 GB / last pushed date : 2021-11-01 09:30:41
repository name : jg-seq-nasnetmobile / repository size : 6.036 GB / last pushed date : 2021-10-29 11:26:35
repository name : jg-seq-mobilenet / repository size : 1.509 GB / last pushed date : 2021-10-28 13:27:11
repository name : jg-lambda-image-efficientnet / repository size : 20.163 GB / last pushed date : 2021-10-26 14:11:42
repository name : jg-lambda-image / repository size : 29.982 GB / last pushed date : 2021-10-26 13:36:27
repository name : jg-lambda-image-nasnetmobile / repository size : 11.384 GB / last pushed date : 2021-10-26 13:36:08
repository name : jg-lambda-ensemble-image / repository size : 6.905 GB / last pushed date : 2021-10-25 05:34:13
repository name : sungjae-spotinfo-ecr / repository size : 1.477 GB / last pushed date : 2021-10-17 16:39:29
repository name : sungjae-ecr-repo / repository size : 1.655 GB / last pushed date : 2021-08-20 13:38:06
repository name : kubia / repository size : 0.264 GB / last pushed date : 2020-05-07 16:49:22
repository name : myapp / repository size : 0.348 GB / last pushed date : 2020-03-02 23:29:19
repository name : fetch_and_run / repository size : 7.906 GB / last pushed date : 2020-01-08 22:24:09
repository name : sss_db / repository size : 0.415 GB / last pushed date : 2019-12-30 13:50:38
repository name : lambda_optimize_serving_arm / repository size : 0.000 GB / last pushed date : 1111-01-01 01:01:01



현재 리전 별 ECR의 repository 현황입니다.

모든 리전의 총 이미지 크기의 합은 775.343 GB이며
그 중 올해 한번도 이미지가 푸시된 적이 없는 이미지 크기의 합은 711.397GB로
올해 한번이라도 푸시된 이미지 크기의 합인 63.946GB와 비교해서 대부분을 차지합니다.
ECR Pricing은 스토리지 GB/월당 0.10 USD 입니다.

올 해 푸시된 적이 없는 이미지들은 전부 지워도 괜찮을까요?

**Comment by kmu-leeky** [comment]
승우야. 잘했다.
무조건 삭제하지는 말고. 우선 지금까지 수집된 리스트를 대상으로 각 지역별, 지역내에서 이미지 크기를 기준으로 내림 차순으로 정렬해서 보여주면 좋을것같아.
전에 보니 가동중인 시간 혹은 생성 시간 기준으로 오래된것은 색갈을 달리해서 표시해주면 좋은것 같아 (서버 중지 시기에 따라서 색갈을 달리 하는것처럼)

우선은 이런 리스트를 매달 초에 한번씩 슬랙으로 자동으로 보내지게 하면 관리에 도움이 될것 같아.

**Comment by seungwoo1124** [comment]
넵 알겠습니다

**Comment by seungwoo1124** [comment]
![스크린샷 2023-11-14 11-12-41](https://github.com/ddps-lab/cloud-usage/assets/56826964/74bb9995-14f3-4d75-b5a4-a4fa6b0d3c53)
슬랙에 보내는 형식은 이렇게 될 것 같습니다. 리전별 이미지 크기를 기준으로 내림차순하고 이미지가 마지막으로 푸쉬된 지 6개월이 지난 repository는 주황색 원, 1년이 지난 repository는 빨간색 원으로 표시하였습니다. 이제 다른 자원 및 계정 사용량의 슬랙 알림 보내는 시간을 정리해서 ecr 알림도 추가하도록 하겠습니다.

**Comment by kmu-leeky** [comment]
오케이 승우야. 정렬은 내림 차순으로 하는게 더 좋을것 같아. 그리고 지금 상황을 한번 보면 좋을것 같으니, 지금 ECR 의 상황을 위의 포맷으로 한번 보내게 해줘.

**Comment by seungwoo1124** [comment]
넵 반영하여 코드 수정후 매뉴얼 작성하였습니다. 확인해주시면 머지 후 이슈 클로즈하고 다음 이슈로 넘어가도록 하겠습니다.

**Comment by seungwoo1124** [comment]
현재 ECR의 이미지들이 사용되고 있는 서비스는
1. lambda
2. ec2 AMI
3. 로컬
인 것으로 보입니다. 로컬에서는 ECR의 이미지를 삭제한다고 해도 로컬 저장소에 백업되어있는 상태이기 때문에 문제는 없을 것을 보이나 lambda나 ec2 AMI에서는 사용중인 이미지를 삭제하면 정상적으로 작동하던 서비스가 갑자기 서비스가 안 될 수 있습니다.
 현재 ecr_management의 동작 방식은 python으로 boto3 SDK를 사용하여 ecr resource를 describe함수를 이용하여 표기하는 방법이었는데, 현재 ecr resource의 describe함수만으로는 사용중인 다른 서비스들을 확인 할 수 없어 lambda 및 ec2도 확인하는 코드 작업 후 서로의 객체를 join하여 확인하는 방법으로 진행하는 것이 좋을 것 같습니다.
 수동으로 전부 확인하기에는 us-west-2 리전의 lambda function 및 AMI의 개수가 많아서 코드를 다시 수정하여 현재 ecr 이미지를 사용중인 서비스들까지 슬랙으로 보내서 각자 확인하고 ecr 이미지 및 연결되어있는 서비스까지 더이상 사용되지 않는 경우 수동으로 삭제하는 것으로 진행해보려고 하는데 괜찮을까요?

**Comment by kmu-leeky** [comment]
현재 만들어진 람다를 쿼리해서 ecr 이미지를 쿼리하면 알수 있겠다.
EC2 AMI 에서는 ECR 을 사용할수 없을것 같은데. 2번도 가능한 시나리오인가?

**Comment by kmu-leeky** [comment]
생각해보면 ECR 이미지가 람다에 연결되어 있다고 하더라고, 해당 람다 자체가 거의 실행이 안되는 것일수 있겠다.
람다의 경우 마지막으로 실행된 시간도 함께 볼수 있다면 좋겠다.

**Comment by seungwoo1124** [comment]
AMI부분은 AMI source 부분이 ecr repository의 uri부분과 유사하여 제가 착각한 것 같습니다.
lambda의 경우 연결되어있다면 마지막 실행된 시간까지 포함해서 출력하게 포맷을 변경해보도록 하겠습니다.

**Comment by seungwoo1124** [comment]
![이미지 1](https://github.com/ddps-lab/cloud-usage/assets/56826964/6b4bf063-1afc-4c38-b0ee-420e634882de)

수정한 슬랙 메시지 형식입니다.
현재 해당 이미지를 사용중인 람다 함수가 있는지, 마지막 실행한 시점은 언젠지 표시하게 했습니다.
boto3로 조회한 ECR, Lambda, CloudWatch 객체를 조인해서 추출하는 방식으로 진행했습니다.
readme.md에 사용법 정리해서 올리겠습니다.

**Comment by kmu-leeky** [comment]
승우야 잘했다. ECR 이미지의 경우 생성된 시간도 추가를 해줄래? 이걸 기준으로 삭제 여부를 선택할수 있겠다.

**Comment by seungwoo1124** [comment]
## 삭제 예정 ECR 리포지토리 및 lambda 함수
### us-west-2
	- 람다 함수 : jg-tvm-test, 마지막 실행시간 : 2022-04-14
- ECR 리포지토리 : mxnet_lambda_container / 53.914 GB
	- 람다 함수 : jg-mxnet-serving, 마지막 실행시간 : 2022-06-15
- ECR 리포지토리 : tvm_lambda_container_arm / 38.758 GB
- ECR 리포지토리 : convert_torch_intel_tvm / 35.529 GB
- ECR 리포지토리 : lambda_archive_module / 30.805 GB
- ECR 리포지토리 : jg-lambda-image / 29.982 GB
- ECR 리포지토리 : convert_torch_arm_tvm / 27.831 GB
- ECR 리포지토리 : onnx_lambda_container / 21.492 GB
- ECR 리포지토리 : jg-lambda-image-efficientnet / 20.163 GB
	- 람다 함수 : convert_torch_intel_onnx, 마지막 실행시간 : 2022-11-06
- ECR 리포지토리 : torch_lambda_container / 18.752 GB
	- 람다 함수 : serving_intel_onnx_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx, 마지막 실행시간 : 2022-08-17
	- 람다 함수 : serving_intel_onnx_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_intel_onnx_512, 마지막 실행시간 : 2022-09-08
- ECR 리포지토리 : jg-seq-ensemble / 16.921 GB
	- 람다 함수 : serving_intel_tvm_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_tvm_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_intel_tvm, 마지막 실행시간 : 2022-09-02
	- 람다 함수 : serving_intel_tvm_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_tvm_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_tvm_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_intel_tvm_1024, 마지막 실행시간 : 2022-09-06
- ECR 리포지토리 : jg-graviton-tensorflow / 12.233 GB
	- 람다 함수 : serving_intel_torch_2048, 마지막 실행시간 : 2023-03-21
	- 람다 함수 : serving_intel_torch_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_intel_torch_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_torch_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_torch_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_torch, 마지막 실행시간 : 2022-09-02
	- 람다 함수 : serving_intel_torch_10240, 마지막 실행시간 : 2022-11-06
- ECR 리포지토리 : jg-lambda-image-nasnetmobile / 11.384 GB
- ECR 리포지토리 : jg-seq-efficientnet / 10.614 GB
	- 람다 함수 : lambda_optimize_serving, 마지막 실행시간 : No Log Group
	- 람다 함수 : lambda-optimize-serving, 마지막 실행시간 : 2022-05-25
	- 람다 함수 : serving_arm_tvm_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_tvm_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_arm_tvm_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_tvm_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_arm_tvm_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_tvm_4096, 마지막 실행시간 : 2022-09-06
- ECR 리포지토리 : lambda_check_module / 9.396 GB
- ECR 리포지토리 : fetch_and_run / 7.906 GB
	- 람다 함수 : serving_arm_onnx_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_arm_onnx_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_arm_onnx, 마지막 실행시간 : 2022-09-02
	- 람다 함수 : serving_arm_torch, 마지막 실행시간 : 2022-09-02
	- 람다 함수 : serving_arm_torch_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_arm_torch_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_10240, 마지막 실행시간 : 2022-11-06
- ECR 리포지토리 : jg-lambda-ensemble-image / 6.905 GB
- ECR 리포지토리 : onnx_lambda_container_arm / 6.296 GB
	- 람다 함수 : jg-lambda-ensemble-nasnetmobile, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : torch_profiler_arm / 5.910 GB
- ECR 리포지토리 : aws_inferentia / 3.476 GB
- ECR 리포지토리 : lambda-container-example / 3.062 GB
- ECR 리포지토리 : serving_mxnet_bert_arm / 2.936 GB
- ECR 리포지토리 : torch_lambda_container_arm / 2.795 GB
- ECR 리포지토리 : tflite_lambda_container / 2.271 GB
- ECR 리포지토리 : sungjae-sps-lambda / 2.240 GB
- ECR 리포지토리 : sungjae-ecr-repo / 1.655 GB
	- 람다 함수 : jg-tfserving-lambda-TensorFlowInferenceFunction-9CYNciRr17BO, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : jg-seq-mobilenet / 1.509 GB
- ECR 리포지토리 : sungjae-spotinfo-ecr / 1.477 GB
	- 람다 함수 : jg-tfserving-mobilenetv2-TensorFlowInferenceFuncti-HTqpYnEEERUU, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : tvm_lambda_container_origin / 1.280 GB
- ECR 리포지토리 : tflite_lambda_container_arm / 1.276 GB
- ECR 리포지토리 : serving_arm_base / 1.177 GB
	- 람다 함수 : jg-xgboost-lambda-XGBoostInferenceFunction-drYLLiKxz2cE, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : sss_db / 0.415 GB
	- 람다 함수 : jg-scikit-lambda-ScikitLearnInferenceFunction-oNO522GbKTOS, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : myapp / 0.348 GB
- ECR 리포지토리 : kubia / 0.264 GB
- ECR 리포지토리 : jgsamfaae96cb/helloworldfunction19d43fc4repo / 0.176 GB
- ECR 리포지토리 : lambda_optimize_serving_arm / 0.000 GB
### us-east-1
- ECR 리포지토리 : ys-profet_for_lambda_container / 5.544 GB
### us-east-2
- ECR 리포지토리 : billing / 0.628 GB
- ECR 리포지토리 : fargate-image / 0.130 GB
### ap-northeast-2
- ECR 리포지토리 : lambda-container-example-yoon / 0.000 GB


위 내용이 삭제 예정 ECR 리포지토리 및 lambda 함수입니다.
- 삭제조건 1 : 현재 이미지를 사용중인 람다 함수가 없고 마지막으로 이미지가 푸시된지 6개월 이상 지난 경우
- 삭제조건 2 : 이미지를 사용하는 람다 함수의 마지막 실행 시각이 1년 이상 지난 경우
입니다. 위 내용을 내일 오전에 슬랙에 다시 올리고 오후 6시 이후에 확인 후 삭제 진행해도 괜찮을까요?

**Comment by seungwoo1124** [comment]
방금 올린 ECR 내용에 오류가 있어 다시 확인해보겠습니다.

**Comment by seungwoo1124** [comment]
## 삭제 예정 ECR 리포지토리 및 lambda 함수
- 삭제 조건 1 : 현재 이미지를 사용중인 람다 함수가 없고 마지막으로 이미지가 푸시 된 지 6개월이상 지난 경우
- 삭제 조건 2 : 이미지를 사용하는 람다 함수의 마지막 실행 시각이 1년 이상 지난 경우
### us-west-2
- ECR 리포지토리 : tvm_lambda_container / 163.220 GB
	- 람다 함수 : jg-tvm-test, 마지막 실행시간 : 2022-04-14
- ECR 리포지토리 : mxnet_lambda_container / 53.914 GB
- ECR 리포지토리 : mxnet_lambda_container_arm / 43.851 GB
	- 람다 함수 : jg-mxnet-serving, 마지막 실행시간 : 2022-06-15
- ECR 리포지토리 : tvm_lambda_container_arm / 38.758 GB
- ECR 리포지토리 : convert_torch_intel_tvm / 35.529 GB
- ECR 리포지토리 : lambda_archive_module / 30.805 GB
- ECR 리포지토리 : jg-lambda-image / 29.982 GB
- ECR 리포지토리 : convert_torch_arm_tvm / 27.831 GB
- ECR 리포지토리 : onnx_lambda_container / 21.492 GB
- ECR 리포지토리 : jg-lambda-image-efficientnet / 20.163 GB
- ECR 리포지토리 : convert_torch_onnx / 19.471 GB
	- 람다 함수 : convert_torch_intel_onnx, 마지막 실행시간 : 2022-11-06
- ECR 리포지토리 : torch_lambda_container / 18.752 GB
- ECR 리포지토리 : serving_intel_onnx / 16.943 GB
	- 람다 함수 : serving_intel_onnx_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_onnx, 마지막 실행시간 : 2022-08-17
	- 람다 함수 : serving_intel_onnx_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_intel_onnx_512, 마지막 실행시간 : 2022-09-08
- ECR 리포지토리 : jg-seq-ensemble / 16.921 GB
- ECR 리포지토리 : serving_intel_tvm / 13.887 GB
	- 람다 함수 : serving_intel_tvm_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_tvm_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_intel_tvm, 마지막 실행시간 : 2022-09-02
	- 람다 함수 : serving_intel_tvm_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_tvm_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_tvm_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_intel_tvm_1024, 마지막 실행시간 : 2022-09-06
- ECR 리포지토리 : jg-graviton-tensorflow / 12.233 GB
- ECR 리포지토리 : serving_intel_torch / 11.675 GB
	- 람다 함수 : serving_intel_torch_2048, 마지막 실행시간 : 2023-03-21
	- 람다 함수 : serving_intel_torch_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_intel_torch_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_torch_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_torch_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_intel_torch, 마지막 실행시간 : 2022-09-02
	- 람다 함수 : serving_intel_torch_10240, 마지막 실행시간 : 2022-11-06
- ECR 리포지토리 : jg-lambda-image-nasnetmobile / 11.384 GB
- ECR 리포지토리 : jg-seq-efficientnet / 10.614 GB
- ECR 리포지토리 : lambda_optimize_serving / 10.397 GB
	- 람다 함수 : lambda_optimize_serving, 마지막 실행시간 : No Log Group
	- 람다 함수 : lambda-optimize-serving, 마지막 실행시간 : 2022-05-25
- ECR 리포지토리 : serving_arm_tvm / 9.724 GB
	- 람다 함수 : serving_arm_tvm_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_tvm_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_arm_tvm_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_tvm_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_arm_tvm_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_tvm_4096, 마지막 실행시간 : 2022-09-06
- ECR 리포지토리 : lambda_check_module / 9.396 GB
- ECR 리포지토리 : fetch_and_run / 7.906 GB
- ECR 리포지토리 : serving_arm_onnx / 7.782 GB
	- 람다 함수 : serving_arm_onnx_10240, 마지막 실행시간 : 2022-11-06
	- 람다 함수 : serving_arm_onnx_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_onnx_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_arm_onnx, 마지막 실행시간 : 2022-09-02
- ECR 리포지토리 : serving_arm_torch / 7.034 GB
	- 람다 함수 : serving_arm_torch, 마지막 실행시간 : 2022-09-02
	- 람다 함수 : serving_arm_torch_1024, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_512, 마지막 실행시간 : 2022-09-08
	- 람다 함수 : serving_arm_torch_8192, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_4096, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_2048, 마지막 실행시간 : 2022-09-06
	- 람다 함수 : serving_arm_torch_10240, 마지막 실행시간 : 2022-11-06
- ECR 리포지토리 : jg-lambda-ensemble-image / 6.905 GB
- ECR 리포지토리 : onnx_lambda_container_arm / 6.296 GB
- ECR 리포지토리 : jg-seq-nasnetmobile / 6.036 GB
	- 람다 함수 : jg-lambda-ensemble-nasnetmobile, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : torch_profiler_arm / 5.910 GB
- ECR 리포지토리 : aws_inferentia / 3.476 GB
- ECR 리포지토리 : lambda-container-example / 3.062 GB
- ECR 리포지토리 : serving_mxnet_bert_arm / 2.936 GB
- ECR 리포지토리 : torch_lambda_container_arm / 2.795 GB
- ECR 리포지토리 : tflite_lambda_container / 2.271 GB
- ECR 리포지토리 : sungjae-sps-lambda / 2.240 GB
- ECR 리포지토리 : sungjae-ecr-repo / 1.655 GB
- ECR 리포지토리 : jgtfservinglambdab907d6f5/tensorflowinferencefunction402a36b7repo / 1.564 GB
	- 람다 함수 : jg-tfserving-lambda-TensorFlowInferenceFunction-9CYNciRr17BO, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : jg-seq-mobilenet / 1.509 GB
- ECR 리포지토리 : sungjae-spotinfo-ecr / 1.477 GB
- ECR 리포지토리 : jgtfservingmobilenetv2201ea088/tensorflowinferencefunction402a36b7repo / 1.418 GB
	- 람다 함수 : jg-tfserving-mobilenetv2-TensorFlowInferenceFuncti-HTqpYnEEERUU, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : tvm_lambda_container_origin / 1.280 GB
- ECR 리포지토리 : tflite_lambda_container_arm / 1.276 GB
- ECR 리포지토리 : serving_arm_base / 1.177 GB
- ECR 리포지토리 : jgxgboostlambdafb3860c3/xgboostinferencefunction8eed4b10repo / 0.727 GB
	- 람다 함수 : jg-xgboost-lambda-XGBoostInferenceFunction-drYLLiKxz2cE, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : sss_db / 0.415 GB
- ECR 리포지토리 : jgscikitlambdad958a065/scikitlearninferencefunctionc862108arepo / 0.350 GB
	- 람다 함수 : jg-scikit-lambda-ScikitLearnInferenceFunction-oNO522GbKTOS, 마지막 실행시간 : No Log Group
- ECR 리포지토리 : myapp / 0.348 GB
- ECR 리포지토리 : kubia / 0.264 GB
- ECR 리포지토리 : jgsamfaae96cb/helloworldfunction19d43fc4repo / 0.176 GB
- ECR 리포지토리 : lambda_optimize_serving_arm / 0.000 GB
### us-east-1
- ECR 리포지토리 : ys-profet_for_lambda_container / 5.544 GB
### us-east-2
- ECR 리포지토리 : billing / 0.628 GB
- ECR 리포지토리 : fargate-image / 0.130 GB
### ap-northeast-2
- ECR 리포지토리 : lambda-container-example-yoon / 0.000 GB



이상 ECR 리포지토리 및 람다 함수 삭제 예정 리스트입니다. 내일 아침에 슬랙에 해당 내용 올리고 저녁6시에 확인후 삭제 진행해도 될까요?

**Comment by kmu-leeky** [comment]
응 승우야. 괜찮아 보인다. 최종 확인 후에 사용중이라고 하는것 외에는 다 삭제해도 갠찮을것 같아.
