### ISSUE TITLE
s3 파일 아카이브 실행을 위한 EC2 서비스 동작 자동화

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#25]
현재 s3 management 보안이 취약한 점을 보완합니다.
또한 자동 관리 될 수 있도록 자동화 과정을 보완합니다.
- userdata 를 사용하여 서버 동작 시 자동으로 파일 정리 기능 추가
- 서버 시작은 람다를 통해서 구동

**Comment by kmu-leeky** [comment]
추천 한가지. 이슈 나 내용을 보면 다들 비슷한것 같아. 조금 더 명시적으로 이야기 할 수 있다면 좋을것 같아.
내가 수정을 해둘께.

**Comment by Kim-Yul** [comment]
## ec2 서비스 동작 자동화 진행중
s3 아카이빙을 자동으로 진행할 수 있게 ec2 서비스를 생성 중입니다.

1. 람다 함수를 통해 ec2 생성
2. user data를 ec2 생성 시 전달
3. user data를 전달받은 ec2 에서 자동화 코드 실행
4. 자동화 코드 실행 종료 후 ec2를 삭제하는 람다 함수 호출
5. 람다 함수를 이용하여 ec2 제거

현재 위의 과정이 이루어지는 ec2 서비스 자동화를 진행 중입니다.
우선 2번까지 진행 완료하였으며, 4번과 5번 코드는 이미 작성해두었습니다.
현재 3번이 원활하게 진행되면 되는데, user data를 통해서 자동화 코드를 실행하는 부분에서 애를 먹고 있어 진행이 더뎌졌습니다.
내일 user data를 통한 자동화 코드 실행부터 이어서 진행할 예정입니다.

**Comment by Kim-Yul** [comment]
현재 s3 거의 대부분이 자동으로 관리되고 있습니다.
다만, 5GB 가 넘는 파일에 대해서는 수동으로 진행되어야 합니다.
이를 자동으로 할 수 있는 방안이 있긴 합니다.
이 방안은 아래에 적어두겠습니다.

모든 작업 완료하였고, aws 내에 반영해두겠습니다.
확인 마치시면 해당 이슈 클로즈하겠습니다.

### 멀티파트 아카이빙
5GB 가 넘는 파일이 존재하는 버킷의 이름과 이 파일에 접속할 수 있는 키를 알고 있다면 멀티파트 아카이빙가 가능합니다.
멀티파트 아카이빙은 5GB로 파일을 쪼개서 아카이빙하게 됩니다.
다만 이 경우 동기적으로 실행하기 때문에 현재 아카이빙을 진행하는 파일에서 함께하는 것은 어려울 것으로 판단됩니다.
현재 아카이빙을 진행하는 파일인 `aws_auto_s3_archiving.py`에서 분리되어 따로 진행되어서 구현해야 할 것 같습니다.

작업이 오래걸린다는 점에서 인스턴스 내에서 실행되어야 할 것 같습니다.
또한, `aws_auto_s3_archiving.py` 가 실행된 이후 멀티파트 아카이빙이 실행되어야 할 것으로 판단됩니다.
현재 archiving 파트에서 파일에 접속할 수 있는 키를 담은 리스트를 생성하고 슬랙으로 출력하고 있습니다.
이 부분에 버킷 이름을 함께 보관하고, 멀티파트 아카이빙을 진행하는 파일에 넘겨주어 실행하게 되면 어떨까 싶습니다.

**Comment by Kim-Yul** [comment]
멀티파트 아카이빙은 새로운 이슈로 남겨두겠습니다. 이슈 클로즈합니다.
