### ISSUE TITLE
spot 실험에서 예상보다 많은 금액이 발생한 이유 분석

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/cloud-usage#3]
초기에 예측했던 금액과 차이가 컸던 이유를 분석해서 공유해주면 다음에 비슷한 실험을 할때 참조할수 있고 도움이 될것 같음.

**Comment by odobenuskr** [comment]
해당 문제의 원인을 발견하고 코드를 수정했습니다
문제의 원인은 workload sampling 과정에서 groupby min 을 사용할 때 column 단위로 min 값이 나타난다는 점을 간과한 것입니다. 단순하게 groupby min 을 쓰면 안되고, 먼저 SpotPrice 로 sorting 한 다음, first 를 추출하는 방법으로 코드를 구성해야 정상적으로 가장 저렴한 워크로드가 추출됩니다. 코드의 수정은 아래와 같습니다.

```
# 이전 코드
cheap_workload_min = cheap_workload.groupby(by=['InstanceFamily', 'Region']).min()

# 수정 후 코드
cheap_workload_min = cheap_workload.sort_values(by=['SpotPrice']).groupby(by=['InstanceFamily', 'Region']).first()
```

아래의 그림은 수정 전 코드에 문제가 되는 부분입니다.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/20024627/179647599-e731aa05-9b72-4587-97dc-8721c0001cb7.png">

아래는 문제 해결을 위해 참고한 자료입니다
https://stackoverflow.com/questions/23394476/keep-other-columns-when-doing-groupby

**Comment by kmu-leeky** [comment]
그러네. 위의 코드에서 생각해보니. group by 후에 어떤행을 기준으로 min 을 계산하는지 표시가 안되어있기도 했네. 어쩌면 지금 정도의 금액이 나온게 다행이라고 생각해야겠다. 빠르게 잘 분석했다. 코드도 잘 반영된듯 하니 이건 close 하자
코드 - https://github.com/ddps-lab/spot-checker/compare/02353929fe7a...82e93e5fc4c6
