### ISSUE TITLE
전혀 사용하지 않는 Resource 조사 및 삭제

### ISSUE THREAD

**Issue by seungwoo1124** [ddps-lab/cloud-usage#34]
전혀 사용하지 않는 Resource들의 billing현황을 조사하고 해당 자원들을 삭제하도록 하겠습니다.

**Comment by seungwoo1124** [comment]
### Amazon macie

- 머신러닝과 패턴 인식 기술 (정규식 등)을 사용하여 S3 버킷 내의 민감한 데이터 감지 서비스
- 민감한 데이터?
    - 주민 등록 번호 등
- 현재 [[bigdata@kookmin.ac.kr](mailto:bigdata@kookmin.ac.kr)](mailto:bigdata@kookmin.ac.kr) 에서 월 3.33$ 부과중입니다.
- 일시 정지 (Suspend), 완전 정지 (Disable) 가 가능합니다
- 정지한다고 해서 S3 버킷에 영향이 가지는 않습니다

### AWS Backup

- 리소스들 (AWS, On-premise 둘 다 가능)의 백업 관리 서비스
- 현재 [[bigdata@kookmin.ac.kr](mailto:bigdata@kookmin.ac.kr)](mailto:bigdata@kookmin.ac.kr) 에서 월 2.33$ 부과중입니다
- 대부분 EFS들과 연결되어있으며 연결된 대부분의 EFS들의 생성 시간이 2021년도 이전입니다.
- Backup Plan 삭제시 연결된 EFS 먼저 삭제 후 Backup을 삭제하는 편이 좋을 것 같습니다.

### Amazon DynamoDB

- No-SQL 키 - 값 데이터베이스 서비스
- 현재 [[bigdata@kookmin.ac.kr](mailto:bigdata@kookmin.ac.kr)](mailto:bigdata@kookmin.ac.kr) 에서 월 0.18$ 부과중입니다.

### Amazon RDS

- AWS클라우드에서 관계형 데이터베이스를 설치, 운영, 확장 할 수 있는 웹 서비스
- 현재 [bigdata@kookmin.ac.kr](mailto:bigdata@kookmin.ac.kr) 에서 월 0.01$ 부과중입니다.
- 현재 Snapshot 120GB로 인해 Backup 요금으로 부과되고 있으며 활성화된 RDS 인스턴스는 없습니다.

**Comment by kmu-leeky** [comment]
승우야. 지난번에 잘 정리한것 같으니 이야기한 내용에 기반해서 조금 더 조사하고 (백업 서비스 등) 삭제 해버리고 이슈 정리하자.

**Comment by seungwoo1124** [comment]
앗 네 알겠습니다 오늘 거의 마무리 돼서 저녁에 바로 정리하겠습니다.

**Comment by seungwoo1124** [comment]
Backup plan의 경우 권한 부족으로 access denied가 떴고 나머지는 삭제 완료하였습니다.

**Comment by seungwoo1124** [comment]
주말간에 Backup plan과 연결된 EFS 자원들 조사해서 삭제 진행해보고 완료되면 이슈 닫겠습니다.

**Comment by seungwoo1124** [comment]
Backup plan과 연결된 EFS랑 사용된지 1년 넘은 EFS들 한번에 삭제 진행하였습니다.
