### ISSUE TITLE
kmubigdata 계정에 있는 s3 버킷 중 이용하지 않는 자원 삭제

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#35]
kmubigdata 계정에 있는 s3 버킷 중에 이용하지 않는 자원을 삭제합니다.
앞으로 이용할 가능성이 전혀 없는 버킷과 사용하지 않는 버킷을 삭제하고자 합니다.
아래는 현재 존재하는 버킷리스트입니다.

버킷의 사이즈 내림차순으로 정렬하였으며, 최근 액세스 날짜와 현재 어떤 스토리지 클래스에 저장되어 있는지를 확인할 수 있습니다. (버킷에 파일을 업로드하지 않은 경우 `2017년 1월` 로 표현됩니다.)
아카이빙되어 있는 버킷 역시 과금이 되기 때문에 불필요한 버킷은 모두 정리하고자 합니다.

<img width="804" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/c0a7dc31-1754-4b3f-a0f4-9b008ce4f5a0">

**Comment by Kim-Yul** [comment]
## 현재 사용하고 있는 s3 버킷
migration-compatibility-detail
migration-compatibility
stablespot-website
spotrank-figure
sungjae-spot-checker-data
sungjae-sps-data
sungjae-spotinfo-data
query-sps-change-targetcapacity
spotrank-data-1day
spotrank-latest
kmkim-spotcheckerexp-240131
kmkim-spotcheckerexp-240109
kmkim-ddd-exp-1121
spot-advisor-for-bedrock

총 14개입니다.
교수님께서도 사용하시는 s3 버킷이 있으시면 그 리스트를 제외하고 삭제하고자 합니다.
확인 부탁드립니다.

**Comment by kmu-leeky** [comment]
유림아. 삭제해도 될것 같아.
그런데 spotrank-figure 저건 뭐길래 180 기가나 사이즈가 되지? 사용을 하는 데이터가 맞을까?

**Comment by Kim-Yul** [comment]
spotrank-figure 는 옛날에 spotlake 논문쓸 때 사용한 figure 자료라고 합니다. 사용하지 않아서 삭제하도록 하겠습니다.
그 외 전부 삭제해도 괜찮을까요? 총 82개의 버킷이 삭제될 예정입니다.

**Comment by kmu-leeky** [comment]
응 유림아 그렇게 하자.

**Comment by Kim-Yul** [comment]
7월 4일 사용하는 13개의 버킷을 제외하고 모두 삭제하였습니다.

**<삭제하지 않은 버킷>**
- migration-compatibility-detail
- migration-compatibility
- stablespot-website
- sungjae-spot-checker-data
- sungjae-sps-data
- sungjae-spotinfo-data
- query-sps-change-targetcapacity
- spotrank-data-1day
- spotrank-latest
- kmkim-spotcheckerexp-240131
- kmkim-spotcheckerexp-240109
- kmkim-ddd-exp-1121
- spot-advisor-for-bedrock

그러나 3개의 버킷에서 문제가 발생하였습니다.
- sungsoo-document-db
- sungsoo-test-db
- sungsu-documentdb

위 3개의 버킷에서는 동일하게 권한 문제가 발생합니다. 제 IAM 계정에는 admin 권한이 있는 상태임에도 권한 오류가 발생하여 삭제가 불가능합니다. 이에 진행이 가능하다면 root 에서 삭제해보는 시도가 있을 것 같습니다. root 계정에서 삭제를 해볼 수 있을까요? 그외 제가 할 수 있는 방향이 무엇이 있을지 계속 찾아보겠습니다.

**Comment by kmu-leeky** [comment]
저건 root 에서도 안 지워졌던 기억이;; 뭐가 문제인지 모르겠네.

**Comment by Kim-Yul** [comment]
앗 그렇군요.. 우선 위 버킷에 내용은 aws팀 case로 문의 넣어보았습니다. 답장이 오는대로 정리하여 별도의 이슈에서 공유하겠습니다.
해당 이슈는 close 하겠습니다.
