### ISSUE TITLE
전날 사용된 인스턴스 및 타입 (스팟/온디맨드)에 대한 리포트

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#38]
현재 존재하는 인스턴스 리포트 정보에 인스턴스가 스팟인지 온디맨드인지에 관한 정보를 추가할 예정입니다.

어떻게 설계할지 아직 정보가 부족하므로 우선 정보 수집 먼저 진행하겠습니다.

1. CloudTrail을 살펴서 기록하는 정보 확인
- 필요한 정보
  - 인스턴스 유형 (스팟/온디맨드)
  - 인스턴스 타입 (ex. t2.micro)
  - 인스턴스 시작 및 중지 시간
  - 인스턴스 사용료

진행해보고 정리하겠습니다.

**Comment by kmu-leeky** [comment]
유림아. 우선 수정할건 지금 제공되는 인스턴스 리포트 정보는 그대로 두고 새로운 메시지를 포스팅 했으면 해.
새로운 메시지에는
그 전날에 시작 된 모든 클라우드 인스턴스를 보이도록.

현재 제공되는 메시지는 특정시간에 동작중이거나 정지 상태인것만 보여주는데,
새로운 메시지에는 이전날에 시작 및 종료된 모든 인스턴스 및 해당 인스턴스의 ondemand, spot 여부 등을 표시.

**Comment by Kim-Yul** [comment]
CloudTrail을 살펴본 결과 공유해드립니다.

### <확인 결과>
1. 인스턴스 유형 (스팟/온디맨드)
  - 위 결과 확인가능합니다.
  - json으로 확인하면 "instanceMarketOptions" 아래 "marketType" : "spot" 으로 분류됩니다.
  - 온디맨드의 경우, 위의 정보가 없으므로 이를 통해 분류 가능할 것으로 판단됩니다.
![image](https://github.com/ddps-lab/cloud-usage/assets/65997015/2348df9c-3a3c-4911-9625-6fb0933c5619)

2. 인스턴스 타입 (ex. t2.micro)
  - 인스턴스 생성 시에만 확인 가능합니다.
  - 중지 후 재시작 할 경우에는 CloudTrail 만으로 확인이 불가능합니다.
  - 재시작할 경우에는 ec2 정보를 가져와 대조해야 할 것 같습니다.

3. 인스턴스 시작 및 중지 시간
  - stop 및 start, run, terminate 시간이 이벤트로 기록되고 있어서 시간 계산이 가능할 것으로 판단됩니다.

4. 인스턴스 사용료
  - bill 에서 확인이 가능하나 특정 인스턴스에 대한 사용료는 측정 불가능합니다.
  - seoul 리전의 t2.micro 인스턴스와 spot 인스턴스의 사용료는 확인이 가능하나, seoul 리전의 t2.micro 인스턴스를 2개 사용한 경우에는 어떤 인스턴스가 어느만큼 사용했는지 확인이 불가능합니다.

### <고민 사항>
현재 CloudTrail은 개인 작업만 보여서 콘솔 상으로는 타 유저의 Run, Stop, Start, Terminate Instance의 정보를 확인할 수 없습니다.
이와 관련하여 boto3로 확인 가능한지 시도해보고자 합니다.

<앞으로 할 일>
boto3를 이용하여 코드 상으로 CloudTrail을 확인해 볼 예정입니다.

**Comment by kmu-leeky** [comment]
"현재 CloudTrail은 개인 작업만 보여서 콘솔 상으로는 타 유저의 Run, Stop, Start, Terminate Instance의 정보를 확인할 수 없습니다."
--> 이건 어떤 이야기야? 유림이 IAM 만 보인다는 이야기야? 그러지 않을것 같아서. 타유저가 누구를 이야기하는지 모르겠네.
인스턴스는 시작-종료 시간 및 타입 정도가 나오면 좋을것 같아.
과금이야 수동으로 계산해도 될것 같아.

**Comment by Kim-Yul** [comment]
콘솔에서는 제 IAM 의 Instance 실행 여부만 확인할 수 있습니다.
다른 분들의 Instance 실행 여부에 대해서는 콘솔 상으로 검색해도 확인이 어렵습니다.
<img width="1188" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/b811fa88-83c6-480c-a970-f5c1398b17b7">
![image](https://github.com/ddps-lab/cloud-usage/assets/65997015/2cecec2e-38e5-4a57-bb98-c5fad92ce9e7)

그래서 오늘 boto3로 확인해볼 예정입니다.

**Comment by Kim-Yul** [comment]
진행 사항 전달해드립니다.
CloudTrail의 경우 리전 별로 이벤트가 분리되어 있었습니다.
그래서 어제는 확인이 불가능한 것처럼 확인이 되었습니다.
타 리전 확인시 정상적으로 Run, Stop, Start, Terminate Instance를 확인할 수 있습니다.

- 도쿄 리전
<img width="1494" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/c14633f8-8c1c-44e5-8701-fbbff6f1b2bf">

- 캘리포니아 리전
<img width="1495" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/1c7cfde1-effc-49ec-867c-d5f5331ddbf1">

boto3로 확인해본 결과, Run, Stop, Start, Terminate Instance 정보를 가져올 수 있습니다.
boto3 CloudTrail의 lookup_events 함수를 이용하여 이 정보를 가져옵니다.
UTC 시간을 기본으로 하고 있어, UTC 시간으로 범위를 지정하면 원하는 시간 대의 이벤트를 확인할 수 있습니다.

- [boto3 SDK docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudtrail/client/lookup_events.html)
- [aws LookupEvents docs](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_LookupEvents.html#awscloudtrail-LookupEvents-request-EndTime)

이전에 미팅에서 말씀해주셨던 내용으로는 데이터베이스에 저장해서 확인하시는 걸 말씀해주셨는데, 현재 Instance report 처럼 전날의 로그를 가져와서 리포트 하는 것이 가능할 것 같습니다.
혹시 데이터베이스에 저장해야 하는 이유가 따로 있을까요?

우선 필요한 정보만 뽑아볼 수 있도록 데이터 필터링 진행하겠습니다.

**필요한 데이터**
- spot 인지 유무
- 인스턴스 리전
- 인스턴스 타입
- 인스턴스 생성자
- 인스턴스 중지 및 시작 시간

**Comment by Kim-Yul** [comment]
진행 사항 전달해드립니다.

### `전날 사용한 인스턴스 리포트` 설계 고민
**DB 저장**
현재 가장 고민하고 있는 사항입니다.
- DB 저장을 꼭 해야 하는가?
  - 우선 DB 저장을 하면 하루 이상 걸리는 인스턴스 작업을 관리하기 용이해집니다.
    예시)
      - 23일 오후 11시 59분에 켠 인스턴스를 24일 오전 1시에 껐을 경우, 23일 사용량에 관하여 필터링을 진행할 경우, 켠 기록은 있는데 끈 기록은 없는 상황이 됩니다. 이와 관련하여 코드 처리를 해야 하는데, DB를 이용하면 이 작업이 용이할 것으로 판단됩니다.
  - DB를 실시간으로 저장해야 하는가?
    - 두 가지 방법이 존재합니다.
      - Run, Start, Stop, Terminate 같은 상황 발생 시 DB에 실시간으로 저장한다.
      - 특정 시간에 boto3 sdk를 이용하여 전날 있었던 일을 DB에 저장한다.
- DB에 저장할 필요가 없다.
  - boto3를 이용하여 슬랙으로 메세지를 보낼 수 있습니다.

### 필요한 데이터 확인
- spot 인지 유무
- 인스턴스 리전
- 인스턴스 타입
- 인스턴스 생성자
- 인스턴스 중지 및 시작 시간
boto3 내에서 모두 확인 가능합니다.
cloud trail을 통해 검색이 가능한 부분입니다.

### 다음 진행
데이터 필터링 코드를 작성할 계획입니다.

**Comment by Kim-Yul** [comment]
진행사항 전달해드립니다.

현재 cloudTrail 만 이용하여 슬랙에 메시지 보내는 작업을 진행하고 있습니다.
다소 복잡하지만, 일차적으로 리전에 존재하는 인스턴스에 대하여 한 개씩 정보를 가져오는 것에 성공하였습니다.

예를 들어
```
도쿄 리전에 인스턴스 1개
서울 리전에 인스턴스 2개
```
라는 상황에서

```
도쿄 리전에 인스턴스 1개
서울 리전에 인스턴스 1개
```

에 대하여 정확한 값을 추출할 수 있습니다.

서울 리전에서 한 개 누락된 것은 누락되지 않도록 수정 중에 있습니다.

또한, 인스턴스가 중복으로 작업한 경우에 대한 것은 아직 관리하고 있지 않습니다.
즉, 인스턴스가 (start-stop-start-stop) 인 경우에 한 번의 (start-stop) 과정만 인식합니다.
모든 과정이 인식되도록 수정할 예정입니다.

<img width="529" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/b8e4c0ea-d166-4c9f-85d6-7ab9523a2353">

현재 테스트한 내용입니다.
보완하여 1차적인 목표에 도달하면 pr올리겠습니다.

다음 진행 사항
1. 한 리전 내의 모든 인스턴스 값 정확히 추출
2. 인스턴스 활성화 시간 계산하여 메세지에 출력
3. 한 인스턴스의 모든 활동 추출

**Comment by kmu-leeky** [comment]
오케이. 유림아 조금씩 진도가 나가는 구나. 한번에 완벽하기 하기보다 이렇게 조금씩 만들어나가면서 공유되는게 좋다.
테스트 워크 스페이스에서 어느정도 작업이 된다면 어려워 하지말고 우리 채널에 추가해서 피드백 주고 받으면서 개발 진행해보자.

**Comment by Kim-Yul** [comment]
#39 해당 풀리퀘를 통해 코드 작업 완료하였으며 다음 작업은 #40 이슈에서 작업합니다.
해당 이슈 완료하여 클로즈 하겠습니다.
