### ISSUE TITLE
중지된 인스턴스 및 전날 사용된 인스턴스 report 시 iam 사용자 이름 추가

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/cloud-usage#43]
슬랙으로 메시지 보낼때 이름을 추가하면 도움이 될듯

**Comment by Kim-Yul** [comment]
### 현재
```
InstanceLaunch (i-07c635433d1790381) / t3a.large / 0:11:05 간 실행
```

### 변경 예정
```
InstanceLaunch (user name, i-07c635433d1790381) / t3a.large / 0:11:05 간 실행
```

이런 식으로 하면 될까요?
이때 들어갈 user name은 aws user 명으로 들어갈 것 같습니다.
또한, aws에서 생성된 인스턴스의 경우 user name에 InstanceLaunch 가 들어갈 수도 있습니다.
현재 코드 동작 상 만약 인스턴스에 이름을 부여하지 않았다면 aws user 가 들어가게 설정되어 있습니다.

**Comment by kmu-leeky** [comment]
응 그러자. 탐지가능한 수준에서 user name 으로 해보자. 그런데 aws 에서 생성된 인스턴스 (InstanceLaunch) 라는건 어떤거야?

**Comment by Kim-Yul** [comment]
<img width="1203" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/6bd8548c-edb5-4cc8-b471-f6eb2f38a9de">

며칠 전 스팟리퀘스트의 생존으로 생성된 인스턴스의 cloudtrail의 로그입니다.
보시면 User name에 InstanceLaunch 라고 작성된 것을 확인하실 수 있습니다.

반면에 제가 오늘 생성한 인스턴스의 로그를 확인해보시면, User name 에 제 aws user 명이 적혀있습니다.

<img width="1196" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/6da4eb0c-e308-488f-8c10-f917d3ff8edf">

스팟리퀘스트의 생존으로 인해, 혹은 서비스 상 특정 User 명 없이 인스턴스가 생성되는 일이 종종 있습니다.
이로 인해 aws에서 user name을 기록하기 위해 InstanceLaunch로 인해 생성되었다고 명명하였고, 특정 user 가 생성하였는지 알 수 없는 경우 user name에 InstanceLaunch가 붙게 됩니다.

**Comment by kmu-leeky** [comment]
@red0sena  경환아. 스팟인스턴스 실험을 하면 InstanceLaunch 로 되는 특별한 이유가 있을까? 스팟인스턴스 실험이라해도 특정 사용자가 인스턴스를 만드니 저렇게 나오면 안되지 않을까 해서. 혹시 테라폼을 사용해서 그런가?

**Comment by mumat0103** [comment]
aws에서 실험 진행할 때, 직접 인스턴스를 생성하는 것이 아닌 스팟 요청을 만들어서 인스턴스를 생성하게 됩니다. 그래서 스팟 요청을 만든 사람은 클라우드트레일에 남게 되는데, 인스턴스를 만든 사람은 InstanceLaunch로 뜨는 것입니다. (두 항목이 다르게 표시됩니다.)
따라서 저번처럼 인스턴스를 종료했음에도 스팟 요청이 다시 인스턴스를 만든 경우 인스턴스를 생성한 사람이 InstanceLaunch로 표기되는 것입니다.

**Comment by kmu-leeky** [comment]
아. 스팟 리퀘스트가 만들었다는 뜻이구나. 해당 스팟 리퀘스트와 인스턴스 정보가 연동되지 않고. 오케이. 확인 땡큐.

**Comment by Kim-Yul** [comment]
진행사항 공유해드립니다.
<img width="1017" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/66dc791b-5b65-43a2-9047-fb8564e095ce">

위와 같은 형식으로 제공될 것 같습니다. aws에서 만들어진 인스턴스의 경우 aws 라는 user name을 임의로 넣었습니다.

또한, 빨간색 네모 칸의 것은 스팟 플릿으로 만들어진 것인데, 두 인스턴스의 경우 누가 만들었는지 명확하지 않아 모니터링이 어려울 것으로 판단되어 인스턴스 key-name을 받아올 수 있도록 조금 수정할까 합니다.
이렇게 진행해도 될까요?

**Comment by kmu-leeky** [comment]
응 좋다. spot fleet 의 경우 그냥 둘까? 아니면 key=name 을 받아오면 조금 더 이해하는데 도움이 될까? 어떤 값들이 오는지 먼저 확인해보고, 좋은 정보라고 판단되면 추가해보자.

**Comment by Kim-Yul** [comment]
#44 풀리퀘를 통해 해당 이슈의 목표를 달성하였으므로 이슈 close 합니다.
