### ISSUE TITLE
daily_instance_report의 4월 26일 us-east-2 리전 사용량 측정 오류 개선

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#45]
<img width="686" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/cbd275c1-a1dd-43ad-ae29-fd7d634cfc1c">

4월 26일 리포트 내용에서 ohio 리전의 사용량 측정이 잘못되었다는 전달을 받아 로그를 확인해보았습니다.
확인 결과 spot 여러 개를 스팟 요청 보냈을 때, [vailduntil 시간으로 스팟 요청을 중지하는 로직](https://github.com/ddps-lab/cloud-usage/issues/40#issuecomment-1968083336)이 이전과 달라 발생한 상황이었습니다.

이전에는 #40 번처럼 해결하면 시간을 측정할 수 있었습니다.
그러나 지금은 userid로 instance id가 들어가도 원하는 이벤트인 DescribeSpotInstanceRequests 를 찾지 못하여 오류가 발생합니다.

<img width="1145" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/ec771df4-006d-4b3a-a17f-5c1ad3a87444">

해결할 수 있는 방법은 이전과 다른 방식으로 spot request id를 찾아 vailduntil 값을 가져오는 것입니다.
현재 찾아본 것은 왜 오류가 발생하는 가에 대해 알아보았고, 코드 작업 진행해도 괜찮다면 이어서 진행하겠습니다!

**Comment by kmu-leeky** [comment]
오케이 유림아. 이유가 어느정도 파악이 되었다면 작업을 해보도록 하자. 어느정도의 노력이 필요할것 같아?

**Comment by Kim-Yul** [comment]
현재 로그를 다시 확인해본 결과 RunInstances 이벤트 내에 spot requests id 가 존재하는 것 같습니다.
이 id를 인스턴스 조회 단계에서 같이 가져올 수 있게 한다면 약 이틀 안에 해결할 수 있을 것 같습니다.

**Comment by kmu-leeky** [comment]
오케이. 그러면 이것까지 한번 진행해보자.

**Comment by Kim-Yul** [comment]
#46 에서 작업 진행하여 람다 및 깃에 반영하였습니다. 해당 이슈 완료하여 close 합니다.
