### ISSUE TITLE
스냅샷 클리닝 중 AMI 비활성화 스냅샷 삭제 제외 처리 필요

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#47]
자세히 알아보아야 하지만, 현재 파악된 부분으로 작성하였습니다.

현재 스냅샷 클리닝 코드는 AMI를 비활성화한 것을 삭제해야 한다고 인식하고 있습니다.
<img width="654" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/deca7b5c-2a0c-4a27-8abd-a114284f4214">

<img width="632" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/da4aabe4-124b-4857-8ab9-a84c699b29fc">

이로 인해 에러가 발생합니다.
로직 상 AMI가 비활성화되어 있어도 스냅샷을 삭제하지 않아야 하는데, 이 경우를 코드에 반영해야 할 것 같습니다.

<img width="387" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/316c0cdd-8ea5-4816-8443-696adceeb9bb">

이 외에 다른 스냅샷은 정상 삭제 되었습니다.

---

다음은 수정이 필요한 부분입니다.
<img width="729" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/a7b0ccfc-3324-446f-a7d4-0cf1ae2690f7">

**Comment by kmu-leeky** [comment]
AMI 가 비활성화  (disable) 되어 있을때 삭제를 하면 안되는데 지금은 삭제를 한다는거지? 그런데 AMI 가 비활성화 되어 있으면 삭제해도 되지 않을까? 비활성화시 삭제 에러가 난다면 그걸 해결해서 삭제되도록 하는게 맞지 않을까?

**Comment by Kim-Yul** [comment]
비활성화된 AMI라면 AMI 삭제 후 스냅샷 삭제로 코드 수정 작업 진행하겠습니다.

**Comment by Kim-Yul** [comment]
원하는대로 코드가 동작하지 않아 수정을 진행하였습니다.
그로 인해 예정보다 하루 늦게 완료되어 뒤늦게 진행 사항 공유해드립니다.

우선, 삭제 전에 리포트해야 할 필요성이 있을 것 같아 리포트 코드 구현했습니다.

<img width="420" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/6607e955-00b1-4e44-bbf7-e9fcbc2b040c">

## 시나리오
report 를 통해서 어떤 snapshot이 삭제될 지 알 수 있으며, management를 통해 ami 삭제 후 실제 삭제가 이루어집니다.

1. AMI 조회 후 `available`로 실제 사용하고 있는 이미지 외에 모두 삭제
2. 스냅샷 조회 후 태그되어 있지 않은 스냅샷 삭제

밑의 AMI 상태와 스냅샷 리스트는 제가 사용하고 있던 리소스입니다.

[활성화 상태의 AMI]
<img width="1200" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/49d73701-1cb2-4eca-adea-48fc12e5005a">

[태그가 있는 상태의 스냅샷]
<img width="1167" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/018cc67f-6308-438a-b932-8dfb69a95137">

### AMI가 활성화 되어 있고, 스냅샷에 Tag가 있는 경우
[결과 : 슬랙 메세지]
<img width="422" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/4f464029-d05e-4f3f-93a9-f8240cb5d686">

### AMI가 활성화 되어 있고, 스냅샷에 Tag가 없는 경우
[태그가 없는 상태의 AMI]
<img width="1163" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/04d5d676-49cf-468d-8a6d-208be468c085">

[결과 : 슬랙 메세지]
<img width="458" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/dc1febdc-c59c-44f4-97c8-b7f37a5c0f42">

### AMI가 비활성화 되어 있고, 스냅샷에 Tag가 있는 경우
[비활성화 상태의 AMI]
<img width="1190" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/51daa609-f8cf-4386-9a4d-4430321cb584">

[태그가 있는 상태의 스냅샷]
<img width="1156" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/130d55ab-f3b1-4d5e-97cd-f63282dd0d27">

[결과 : 슬랙 메세지]
<img width="408" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/9e7b95b6-11c8-4ec3-a335-042d8e839172">

### AMI가 비활성화 되어 있고, 스냅샷에 Tag가 없는 경우
[비활성화 상태의 AMI]
<img width="1188" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/ba29ac29-17ce-4e3c-ae70-06edcbf8776d">

[태그가 없는 상태의 스냅샷]
<img width="1153" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/b80ba257-6adb-4bf9-9225-8196f5d0f927">

[결과 : 슬랙 메세지]
<img width="365" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/65997015/60a96758-bb65-445c-9e85-82ba10bf8c11">


---

이전 코드는 불필요한 코드가 추가되어 있었고 무엇보다 원하는 동작대로 진행되지 않아 의도에 맞게 코드를 간결하게 수정하였습니다.
작성 완료된 코드는 커밋하도록 하겠습니다. 코드 리뷰 후 머지하도록 하겠습니다.

**Comment by Kim-Yul** [comment]
풀리퀘 완료하여 이슈 클로즈 하겠습니다.
