### ISSUE TITLE
스페인 대학에 제공한 API에서 예상치 못한 과금 발생

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/cloud-usage#49]
spotrank에서 다음과 같은 예상 외의 Athena 비용 발생
```
Amazon Athena: $1.98875
        USW2-DataScannedInTB: $1.98875
```

확인하여보니 스페인 대학 쪽에 SpotLake데이터를 제공하기 위해 만든 API에서 과금이 발생
Athena 쿼리문이 문제가 되는것으로 예상 확인 필요

**Comment by red0sena** [comment]
## Athena 스캔범위 줄이기 위한 파티셔닝 적용

기존 아테나 쿼리는 파티셔닝이 적용되어있지 않아 매 쿼리시마다 5.8GB의 데이터를 계속 스캔하였습니다.

<img width="890" alt="Screenshot 2024-06-04 at 11 09 24" src="https://github.com/ddps-lab/cloud-usage/assets/106056971/ec77b12a-5c23-4fbd-bab6-1fe5a4440869">

아래 링크에서 Athena도 파티셔닝 적용이 가능하다는 것을 알아내었습니다.

https://docs.aws.amazon.com/athena/latest/ug/partition-projection-supported-types.html

spotlake 데이터 날짜를 기준으로 year, month, day 파티션 컬럼을 지정하여 쿼리를 진행하니 
<img width="890" alt="image" src="https://github.com/ddps-lab/cloud-usage/assets/106056971/026fba86-2774-4c8e-8eb1-7df6d5f1c98d">


같은 쿼리 결과를 얻으면서 5.8GB -> 43.31 MB로 스캔 데이터를 줄일 수 있었습니다. 
해당 방법 적용하도록 하겠습니다.

**Comment by red0sena** [comment]
실제 API에도 적용 완료하였습니다.

**Comment by kmu-leeky** [comment]
nice!

**Comment by red0sena** [comment]
완료하였으므로close하겠습니다
