### ISSUE TITLE
DynamoDB 과금 내역 확인

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/cloud-usage#52]
### DynamoDB 과금 내역 분석

```
Amazon DynamoDB: $0.0183568218
        SAE1-WriteRequestUnits: $0.0027
        EUW2-WriteRequestUnits: $0.0021422778
        EUW3-WriteRequestUnits: $0.002137824
        EU-WriteRequestUnits: $0.00203544
        USW1-WriteRequestUnits: $0.002007648
        EUN1-WriteRequestUnits: $0.001933632
        USE2-WriteRequestUnits: $0.0018
USW2-WriteRequestUnits: $0.0018
        WriteRequestUnits: $0.0018
```

위 과금 내역에 대해서 확인해보았습니다. 대부분 규민님이 진행하는 DDD 와 관련된 테이블이었고, 재일님이 진행하시는 stablespot 과 관련된 테이블이 1개 있었습니다.

위 로그에서 EU 로 출력되는 Region 은 eu-west-1 이었습니다.

아래는 각 테이블의 Region, Name, Creation Time 을 정리한 표입니다.
| Region | Name | CreationTime |
|---|---|---|
| us-east-2 | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:27:16 |
| us-west-1 | concurrent_execution | 2019년 4월 10일 수요일 오후 3:59:03 |
|  | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:28:02 |
| us-west-2 | jg-tutorial-terraform-lock | 2023년 3월 17일 금요일 오후 8:46:30 |
|  | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:28:46 |
|  | lambda-ensemble1 | 2021년 10월 22일 금요일 오후 4:18:47 |
|  | stablespotDynamoDB | 2024년 3월 25일 월요일 오후 2:14:51 |
| eu-west-1 | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:22:50 |
| eu-west-2 | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:23:41 |
| eu-west-3 | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:24:39 |
| eu-north-1 | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:21:59 |
| sa-east-1 | kmkim-DDDCHECKTABLE | 2024년 1월 30일 화요일 오후 3:25:33 |

**Comment by QueueMin** [comment]
과거 DDD 실험을 위한 IaC 코드 테스트 과정에서 임시로 생성된 자원이 올바르게 정리되지 않은 것 같습니다.
더이상 사용되지 않는 자원이므로, 각 리전에 있는 kmkim-DDDCHECKTABLE은 삭제 처리 하였습니다.
추후 실험을 다시 진행하는 경우, 위 같은 문제가 발생하는지 확인 및 수정 후 진행하겠습니다.

**Comment by mumat0103** [comment]
아래 3개 테이블은 사용하지 않는 것으로 확인하여 삭제하였습니다.

```
concurrent_execution
jg-tutorial-terraform-lock
lambda-ensemble1
```

**Comment by mumat0103** [comment]
자원 정리 하였으므로 Close
