### ISSUE TITLE
S3 아카이빙 자동화 문제 해결

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#53]
8월 6일에 Standard 타입에서 Glacier 타입으로 아카이빙이 자동화 되어야 했을 시스템이 에러로 인해 작동하지 않았습니다. 문제 해결 및 정상적으로 자동화될 수 있도록 수정하는 작업을 진행합니다.

<img width="637" alt="image" src="https://github.com/user-attachments/assets/bef3aac4-bd43-48df-b16b-9ff56928c35f">

Lambda 함수로 ec2 를 실행시키는 데, ami 와 snapshot 삭제를 진행하면서 기존의 ami 를 건들였던 것 같습니다. 이로 인해 변경된 ami id 를 인자로 전달하지 않은 탓에 에러가 발생하였고, 시스템이 정상 수행되지 않았습니다.
에러를 수정하고, 정상 수행되도록 문제를 해결하고자 합니다.

기존 id : ami-0a287f395304484b1
변경 id : ami-0d598c34f28d018eb

**Comment by kmu-leeky** [comment]
유림아 확인 잘했다. 고생했다!

**Comment by Kim-Yul** [comment]
#54 코드 수정하였습니다.
해당 사항은 aws 내에 있는 snapshot 에도 반영하였으며, 새롭게 ami 를 생성하였습니다.

새로 만든 ami id 는 ami-063fffa43fba5ac76 이며, lambda에도 반영해두었습니다.

자동화 문제는 해결하였으며 더 발견된 에러가 없어서 현재 이슈는 확인 후 닫으려고 합니다. 새로운 이슈 발생 시 10월에 다시 추적하도록 하겠습니다.
