### ISSUE TITLE
daily usage 에러 수정

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#55]
## 문제확인
8월 13일 서울리전의 데일리 인스턴스 사용량 시스템에 에러가 생겨 정상적으로 수집되지 않는 경우가 있었습니다.

<img width="416" alt="image" src="https://github.com/user-attachments/assets/7994f0ea-7647-4709-b19a-02d3333f3bb4">

확인해보니 아래와 같이 스팟 인스턴스가 아닌 경우의 인스턴스 아이디를 수집하는 과정에서, 리턴하는 값의 타입이 튜플로 반환되지 않아 문제를 일으키고 있었습니다.

## 작업내용

변경 전 코드
<img width="454" alt="image" src="https://github.com/user-attachments/assets/9f58eb9f-5d14-45fe-952c-3e3a668bc8d4">

변경 후 코드
<img width="485" alt="image" src="https://github.com/user-attachments/assets/ef2640e3-96de-4eff-87f7-d9e81a8a5cf5">

변경 전에는 인스턴스 아이디만 리스트에 담겼으나, 변경 후에는 리스트에 튜플 형식으로 인스턴스 아이디와 None이 담깁니다. None은 스팟 인스턴스가 아니라는 것을 의미합니다.
즉, 변경 전에는 ['i-0ac3eb09e0a293d3a'] 로 담겼다면, 변경 후에는 [('i-0ac3eb09e0a293d3a', None)] 로 담깁니다.

이는 추후에 인스턴스의 정보를 담을 때 반복문에서 에러가 발생하던 문제를 해결할 수 있습니다.
<img width="482" alt="image" src="https://github.com/user-attachments/assets/2e967812-236c-4c6f-85b4-e97c35448364">

## 수정결과
<img width="448" alt="image" src="https://github.com/user-attachments/assets/75615855-a1b5-4448-a96a-87c7cc9d5901">

현재 람다의 코드는 수정해둔 상태입니다. 이전 풀리퀘가 머지된 이후 깃헙 코드에도 반영해두겠습니다.

**Comment by kmu-leeky** [comment]
오케이 유림아 잘 발견해서 수정했네. 이 문제가 생긴 이유가 AWS 에서 제공되는 데이터 타입이 변경되어서인거야? 아니면 원래 있던 현상인데 우리가 처리를 안하고 있었던건가?

**Comment by Kim-Yul** [comment]
현재 발생되고 있던 에러는 온디맨드 인스턴스를 터미네이트 시킬 때의 정보를 수집하는 과정에서 발생하였습니다. 코드를 작성할 당시 이 부분의 코드를 작성하고, 제대로 실행되는지 확인했어야 했는데 스팟 인스턴스를 사용하던 당시라 온디맨드 인스턴스 사용량에서 발생하는 에러를 제가 확인하지 못하고 넘어갔던 것 같습니다. 에러 발생 부분을 확인하고, 시스템과 호환될 수 있도록 데이터 타입을 수정하였습니다.
결론적으로 AWS에서 제공하는 데이터 타입과는 상관이 없습니다.

**Comment by kmu-leeky** [comment]
온디맨드 인스턴스구나. 확인 땡큐.
