### ISSUE TITLE
인스턴스 리포트 에러 디버그

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#56]
## 문제파악
13일 밤부터 사용하고 있는 인스턴스를 슬랙에 알려주는 시스템이 작동하지 않았습니다. 이점이 이상하여 확인해보니 2가지 문제점으로 작동하고 있지 않았습니다.

1. 에러를 슬랙에 보내는 URL 변수가 지정되지 않아 슬랙으로 에러사항이 전달되지 않았습니다.
2. 인스턴스를 사용할 때 keypair를 입력하지 않을 수 있다는 점을 간과하여 문제가 발생하였습니다.

### 1번의 경우
Deploy 하는 과정에서 aws 내 문자열이 의도대로 저장되지 않는 경우가 종종 발생하는데, 이로 인해 `SLACK_DDPS` 로 저장되어야 할 문자열이 `SLACK_DD` 로 잘못 입력되어 있었습니다. 이 부분 수정하여 에러 내용을 확인해보니 아래와 같았습니다.

<img width="430" alt="image" src="https://github.com/user-attachments/assets/910c35d4-90a6-4609-8890-f1c84d1d9398">

### 2번의 경우
keypair 를 지정하지 않고 인스턴스를 사용할 수 있다는 점을 간과하여서 발생한 문제입니다. 인스턴스에 키페어를 지정하지 않아도 사용할 수 있다는 점은 알고 있었지만, 랩실에서 이용할 때 당연히 키페어를 이용할 것이라는 편견으로 반드시 키페어가 있을 것이라는 가정 하에 코드를 작성했던 것 같습니다. 해당 부분은 키페어가 없어도 작동할 수 있도록 수정 진행하였습니다.

## 최종출력
<img width="640" alt="image" src="https://github.com/user-attachments/assets/6d37aa74-43d0-4a0b-9a2a-9df0fa07d778">

#54 의 코드 리뷰 후 이슈 클로즈하겠습니다.

**Comment by kmu-leeky** [comment]
오케이 유림아 잘 작업했다.

**Comment by kmu-leeky** [comment]
PR 내용을 확인했는데, 해당 코드로 2개 문제가 어떻게 해결될런지 잘 보이지는 않네. 코드도 함께보고 머지하자.
