### ISSUE TITLE
EC2 Report 디버깅 및 기능 추가

### ISSUE THREAD

**Issue by Kim-Yul** [ddps-lab/cloud-usage#59]
오전 8시 30분과 오후 10시에 cloud-usage slack 에 리포트 되는 EC2 Report 기능에 디버깅이 필요한 부분과 추가되어야 하는 기능이 있습니다.

이 이슈에서는 EC2 Report에 디버깅 및 기능 추가를 진행합니다.

### 디버깅
<img width="823" alt="image" src="https://github.com/user-attachments/assets/7b2e9162-0aae-4190-8b6e-0f3b319c0755">

시간이이 음수로 측정되어 빨간 불이 뜨는 경우가 있습니다.
이에 대한 원인 파악 및 디버깅이 필요합니다.

### 기능 추가
Callisto에서 사용을 중지해두게 되면 인스턴스는 사라지지만 볼륨은 남기 때문에 이 내용이 사용하지 않는 것처럼 리포트 될 수 있습니다.
따라서 Callisto에서 사용하는 볼륨을 특정하여 따로 리포트하거나 리포트 조건을 바꿔야 할 필요가 생기어 기능을 추가해야 합니다.
이 부분은 무현님과 얘기한 후 코멘트 남기겠습니다.

**Comment by QueueMin** [comment]
시간이 음수로 나오는 이유는 다음과 같습니다.
현재는 인스턴스 가동 시간이 찍히는 로직은

1. 람다 핸들러 호출과 함께 현재 시간(기준시간)을 기록
2. 이후 instance_management(utc_time)을 호출하여 EC2 정보들을 수집 시도.
  a. EC2 describe 후 (현재 시간(기준 시간) - 인스턴스 생성 시간)을 수행하여 현재 실행중인 인스턴스의 가동시간을 계산
3. ~후략.

```py
# lambda handler : 람다 실행
def lambda_handler(event, context):
    utc_time = datetime.now(timezone.utc)
    korea_time = (utc_time + timedelta(hours=9)).strftime("%Y-%m-%d %H:%M")

    head_message = f"Account: {os.environ['EMAIL']}\n"
    head_message += (korea_time+"\n")

    try:
        running_instances, stopped_instances, orphaned_volumes  = instance_management(utc_time)
        message = created_message(head_message, running_instances, stopped_instances, orphaned_volumes)
        response = slack_message(message)
        return "The Instance List was successfully sent in a Slack. Check the Slack message."
    except Exception as e:
        send_slack_message(f"인스턴스 관리가 정상적으로 이루어지지 않았습니다.\n{e}")
        return "This instance management was failed. Check the Code or instances in aws."
```

이때, 1 ~ 2-a 단계 사이에서 인스턴스가 생성이 되면 인스턴스 생성 시간이 기준 시간보다 근소하게 미래가 되고, 이 경우 datetime 모듈에서는 음수 시간 차이를 -1일과 양수 시간으로 출력하여 usage에 이상한 결과가 출력되었습니다.
따라서 기준 시간이 EC2 describe 이후로 지정하는 등의 조치가 필요할 것 같습니다.

datetime 모듈에서 발생한 오류의 예시를 첨부합니다.
<img width="355" alt="image" src="https://github.com/user-attachments/assets/d2813d35-90c9-4270-996b-ef5876a01ada">

**Comment by Kim-Yul** [comment]
확인해주셔서 감사합니다.
내용 참고하여 에러 사항 수정하도록 하겠습니다.

또한, callisto volume 과 관련하여 Callisto volume 이 따로 떨어진지 2주일이 지났을 때만 리포트하는 식으로 수정하겠습니다.

이후 내용은 커밋으로 전해드리겠습니다.

**Comment by Kim-Yul** [comment]
#60 커밋으로 해당 에러 사항 맟 기능 추가 완료했습니다. 본 이슈는 클로즈하겠습니다.
