### ISSUE TITLE
현재 연구실 계정에서 구동중인 (running, stopped) EC2 인스턴스를 탐지 및 슬랙에 공지하는 기능 구현

### ISSUE THREAD

**Issue by kmu-leeky** [ddps-lab/cloud-usage#9]
Boto3 를 활용하여 모든리전에 있는 stopped, running 인 인스턴스를 확인하는 모듈 구현
해당 모듈을 주기적으로 구동하여 연구실 슬랙에 공지해주는 기능 구현

**Comment by Chaewon14** [comment]
교수님, 현재까지 각 리전별로 running 상태인 인스턴스의 데이터들을 모두 가져오는 부분까지 코드 작성을 완료했습니다.

일단 제가 생각하기로는 이 공지의 핵심 기능이
"연구실 사람들에게 현재 running 중인 EC2 인스턴스가 뭐뭐 있는지 주기적으로 알리는 것"이라고 생각합니다.
따라서 알림이 뜨는 시각은 모두들 하루 업무가 끝난 _**'저녁 9시'**_ 에 하고,
알림 텍스트 형식은 _**[리전 / 인스턴스 타입 / 인스턴스 ID / 네임 태그]**_ 로 하는 것이 좋을 것 같다고 생각합니다.
특히나 그날 하루동안 얼마가 들었는지 '비용'에 대해서는 기존의 cloud-usage 기능과 유사하고, 본 알림의 핵심 기능과 거리가 먼 거같아 EC2 알림에는 빼보았는데 괜찮을까요?
그리고 '시간'에 대해서는 해당 인스턴스가 언제부터 running 상태였는지를 표시하는 방법이 가장 적당해 보였는데, 찾아보니까 인스턴스를 처음 생성한 LaunchTime에 대한 정보는 있어도 running이 되기 시작한 시각을 표시할 수 있는 방법은 알아내지 못했습니다...

그래서 위와 같은 형식의 예시는 아래와 같을 것 같습니다.
(현재 실제 running 중인 EC2 인스턴스들 입니다!)

[Running EC2 Instance]
ap-northeast-2 / t3.large  / i-0a0ccbef1abc384e9 / mhsong-bench-instance
us-west-2 / t3.micro / i-0666b130a7112509a / jaeil-sps-collect

**Comment by kmu-leeky** [comment]
오케이. 좋네요. 
공지는 그렇다면 하루 2번 정도하면 좋을것 같아요. 하루 일과 및 실험이 마무리될 확률이 높은 시점. 그리고 하루 일과를 시작할 시점인 아침 8시 30분 정도가 좋을것 같아요.
구동 시작한 시간의 경우 launch time 이 당시에 구동을 시작한 시간이지 않을까요? 
예를 들어 start->stop->start->stop->start 된다면 launch time 은 제일 처음 start 시간 인가요? 아니면 중간에 계속 업데이트 되는 start 시간인가요? 제 생각엔 지속적으로 start 시간으로 업데이트가 된다면 좋을것 같아요.

**Comment by Chaewon14** [comment]
아! 다시 찾아보니 LaunchTime이 인스턴스가 제일 처음 생성된 시간이 아니라 중간에 running 상태로 바뀌면 업데이트 시간이라고 합니다.
교수님, 일단 언제부터 running 상태인지는 나타나있지 않은, running 및 stopped 상태인 EC2 인스턴스 알림만 먼저 테스트해보았습니다. running 중인 인스턴스는 연두색 동그라미를, stopped 인스턴스는 흰색 동그라미 이모지를 같이 나타내서 시각적으로 running 인스턴스가 주목되도록 해보았습니다.
그리고 여기서 running 중인 인스턴스들만 추가적으로 'running 중인 시간'을 같이 표시하는 게 좋을지 교수님께서 보시고 말씀해주시면 반영하도록 하겠습니다!

그리고 공지 알림이 구동되는 시간은 **아침 8시 30분**과 **저녁 10시**(주변 연구실 사람들의 말로는 9시에도 여전히 작업 중일 수 있기 때문에 10시가 좋을 것 같다고 하셨습니다.)로 하겠습니다!

**Comment by kmu-leeky** [comment]
이모지 좋네요 ㅎㅎ 시간 같은 경우 launch time 을 보여주고, 가능하면 현재 시간 기준으로 얼마동안 구동중인지 보여주는것도 좋은 생각인것 같아요.  시간도 좋아요.

**Comment by Chaewon14** [comment]
네! EC2 인스턴스의 LaunchTime(runnig상태가 된 시각)부터 현재까지 얼마간의 시간동안 구동중인지에 대해 뒤에 나타내보았습니다. 추가적으로, 공지 첫 문장에 "Account: bigdata@kookmin.ac.kr"이 있는데, 이전 usage-report를 참고해서 넣어두긴 했지만 무슨 역할을 하는건지, 그리고 그대로 두어야 할지 궁금합니다.

![image](https://github.com/ddps-lab/cloud-usage/assets/83703870/16057afd-71c2-4e89-8e24-a552cfcdb062)

**Comment by kmu-leeky** [comment]
Account 정보는 연구실에서 사용하는 계정이 많다보니 계정을 분리하기 위해서 작성해둔거라 크게 신경 안써도 괜찮을듯 해요. 지금 포맷 아주 좋네요. 이대로 해서 람다 통해서 구동되게끔 머지해봅시다.

**Comment by Chaewon14** [comment]
datetime 시간과 관련하여 오류가 몇가지(타임존, 실행시간 잘못 계산 등)가 좀 있어서 그 부분들만 수정하고 머지 완료했습니다!🙆🏻‍♀️

**Comment by kmu-leeky** [comment]
ㅎㅎㅎ 잘했네요. 수고 많았어요. 내일 동작하는 걸 보고 다른 계정에도 확대 적용해도 괜찮을듯 하네요. 다른 계정에 배포는 @red0sena  이가 해주면 좋을듯.

**Comment by kmu-leeky** [comment]
채원학생. 잘 했는데 생각해보니 디렉토리 위치가 최상위에 있을 필요는 없을것 같아요. 파일이름을 aws_ec2_monitor.py 정도로 바꿔서 monitor 디렉토리 하위에 위치 시켜도 좋을것 같아요

**Comment by kmu-leeky** [comment]
해당 이슈가 close 되지 않아서 한가지 기능 추가 요청.
stop 인 인스턴스의 경우 stop 상태로 있는 시간을 함께 보여주면 좋을듯 해요.
stop 인스턴스에 대해서도 관리가 필요할듯 해서요.

**Comment by Chaewon14** [comment]
stopped 시간 측정하는 기능 포함 + 파일 위치 이동하고 머지까지 완료했습니다! 이제 이슈 close 하겠습니다:)
